### ISSUE TITLE
Need help for browser install of TC exam

### ISSUE THREAD

**Issue by BUTTERJAAM** [tecnickcom/tcexam#10]
Hi, 

When i perform browser installation of TCEXAM on my domain tcexam.butterjaam.in I experience following errors. Additionally When i try to accecc my website it has many errors and warnings
Installation error
start TCExam installation............[OK]
start database installation.........[OK]
create or replace database and get connection........[OK]
create database tables.......... [OK]
fill tables with default data... [OK]
end database installation...........[OK]
start config files update...........[OK]

Warning: rename(../shared/config.default,../shared/config) [function.rename]: No such file or directory in /home/butterja/public_html/tcexam/install/tce_functions_install.php on line 261

Warning: rename(../admin/config.default,../admin/config) [function.rename]: No such file or directory in /home/butterja/public_html/tcexam/install/tce_functions_install.php on line 262

Warning: rename(../public/config.default,../public/config) [function.rename]: No such file or directory in /home/butterja/public_html/tcexam/install/tce_functions_install.php on line 263
start process tce_db_config.php file:
open file.................[OK]
read file.................[OK]
update value 0 ...........[OK]
update value 1 ...........[OK]
update value 2 ...........[OK]
update value 3 ...........[OK]
update value 4 ...........[OK]
update value 5 ...........[OK]
update value 6 ...........[OK]
write file................[OK]
close file................[OK]
end process tce_db_config.php file
start process tce_paths.php file:
open file.................[OK]
read file.................[OK]
update value 0 ...........[OK]
update value 1 ...........[OK]
update value 2 ...........[OK]
update value 3 ...........[OK]
write file................[OK]
close file................[OK]
end process tce_paths.php file
end config files update.............[OK]
end TCExam installation..............[OK]

Website error http://tcexam.butterjaam.in

Plz help me with these issues. I'm a  student and i wish to know more abt it

regards

Ashok

**Comment by thaez** [comment]
KINDLY HELP, I HAVE BEEN GETTING THIS ERROR BELOW WHILE INSTALLING TC EXAM WITH WAMP...KINDLY HELP
Please wait, this installation may take a while...

start TCExam installation............[OK]
start database installation.........[OK]
create or replace database and get connection........[OK]
create database tables.......... 
( ! ) Fatal error: Maximum execution time of 120 seconds exceeded in C:\wamp\www\tcexam-master\shared\code\tce_db_dal_mysqli.php on line 87
Call Stack
#	Time	Memory	Function	Location
1	0.0010	316256	{main}( )	..\install.php:0
2	0.0020	407192	F_install_database( )	..\install.php:85
3	14.5138	436784	F_execute_sql_queries( )	..\tce_functions_install.php:68
4	113.1155	486272	F_db_query( )	..\tce_functions_install.php:129
