### ISSUE TITLE
Using CAS

### ISSUE THREAD

**Issue by pumamammal** [tecnickcom/tcexam#100]
I tried using new feature with tcexam, 
the CAS, i enabled it....i guess am having problem where it says "where is the CAS hosted" 

can i get more explanation on the use of CAS 

One more thing...
I have been lazy about setting up PHPMAILER
Who can gimmie the steps...making it more simple in explanation

One wish.. own a picture with nick....

Thanks

**Comment by nicolaasuni** [comment]
Please check the source code documentation in shared/config/tce_cas.php
