### ISSUE TITLE
Could us implement primary keys inside tcexam tables ?

### ISSUE THREAD

**Issue by peppelinux** [tecnickcom/tcexam#103]
Is there the possibility to insert a autoincrement PK column, for every SQL tables, in the next release of txexam, or in the current ?

**Comment by infohtreasure** [comment]
What are you trying to achive bro ?

On Tue, Mar 10, 2015 at 11:49 AM, peppelinux <notifications@github.com>
wrote:

> Is there the possibility to insert a autoincrement PK column, for every
> SQL tables, in next release of txexam or in the current ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/103>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*

**Comment by peppelinux** [comment]
My mistake !

I made an integration with django and in tables like tce_testgroups I needed to create an exclusive PK for preventing problems. But we cannot take this as an issue, so I closed this thread immediately.

**Comment by infohtreasure** [comment]
Ok good

On Wed, Mar 18, 2015 at 3:37 PM, peppelinux <notifications@github.com>
wrote:

> My mistake !
>
> I made an integration with django and in tables like tce_testgroups I
> needed to create an exclusive PK for preventing problems. But we cannot
> take this as an issue, so I closed this thread immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/103#issuecomment-82999268>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*
