### ISSUE TITLE
Browser installtion

### ISSUE THREAD

**Issue by rassifaerd** [tecnickcom/tcexam#104]
I try to install tcexam on windows 7 with xampp, after Installation , when i logon and try to create something, get always the following error:
ERROR: [2] mysqli_query() expects parameter 1 to be mysqli, null given | LINE: 87 | FILE: C:\xampp_2\htdocs\tcexam-master\shared\code\tce_db_dal_mysqli.php
The Programm function properly, and i can create alle the item ( Test, user, group,etc) but at the bottem of the website i get always the mentioned ERROR:[2] ... message.
Could someone please help with that?

**Comment by nicolaasuni** [comment]
Please be sure you are using the latest TCExam version and the correct mysql driver (mysqli), you can select it during the installation.

**Comment by rassifaerd** [comment]
Thank you very much for you answer, Mr Nicolaasuni
Unfortunately i install the lastst Version of xampp 5.6.3 and the TCExam version form you download website, but I still get the same upon mentined  ERROR message. you means during xampp installtion? 
Best regards
Rassi
