### ISSUE TITLE
import questions TCExam

### ISSUE THREAD

**Issue by nismaty** [tecnickcom/tcexam#105]
Hello,

help please, 
How can i import and use questions using xml?
Need Advice.. Upload works.. where will all the questions go?

Thank you,

**Comment by infohtreasure** [comment]
I don't think you have any issue as you have said upload works!

The questions will be under your define Module and Topics


Thanks

On Fri, Apr 3, 2015 at 10:09 AM, nismaty <notifications@github.com> wrote:

> Hello,
>
> help please,
> How can i import and use questions using xml?
> Need Advice.. Upload works.. where will all the questions go?
>
> Thank you,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/105>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*

**Comment by nismaty** [comment]
No i dont know how i can import a questions using xml?
for exemple i have 100 questions and i need know how i can import a questions without entering question by question 
i need a guide or a description

**Comment by nismaty** [comment]
No i dont know how i can import a questions using xml?
for exemple i have 100 questions and i need know how i can import a questions without entering question by question 
i need a guide or a description

please can you help me

**Comment by nismaty** [comment]
but how can i import a questions using xml i need a description please.

2015-04-03 11:52 GMT+01:00 Hideen Treasures <notifications@github.com>:

> I don't think you have any issue as you have said upload works!
>
> The questions will be under your define Module and Topics
>
>
> Thanks
>

**Comment by nicolaasuni** [comment]
TCExam can import from XML or TSV (tab-separated values) files.
The XML must but in the TCExam format.
The format is pretty simple, for a quick example you should create manually some questions and export them in XML. Then use the resulting XML file as a model for your import.

**Comment by nismaty** [comment]
Can you explain to me M.nicolaasuni how can'i export questions in xml or TSV file for use the resulting file as a model 
Thank you so much for your speedy assistance

**Comment by nismaty** [comment]
Can you explain to me M.nicolaasuni how can'i export questions in xml or
TSV file for use the resulting file as a model
Thank you so much for your speedy assistance

2015-04-12 9:17 GMT+01:00 Nicola Asuni <notifications@github.com>:

**Comment by nicolaasuni** [comment]
Just go to the questions list and press the XML button!

**Comment by nismaty** [comment]
Thank you so much for your speedy assistance...that functions well

**Comment by ugoxuqu** [comment]
Hi Nicola. thanks for the great job. Kindly, I followed your explanation here to import questions and it shows sending successful and import complete, but I don't see the questions when I check in the questions section. What can I do?

MESSAGE: GRAPHICS_DESIGN.xml: file sent correctly
MESSAGE: XML importing completed

**Comment by c72578** [comment]
Have you got php-xml installed?
BTW, which OS are you using?

**Comment by harshala21** [comment]
Hi Nicola, 

1. I've uploaded TSV file for importing questions, file is uploaded successfully and I found it under "cache" folder. Permissions and ownership is set correctly but still I don't see additional questions in my list. 
What should I do?
OS: Ubuntu 14 

2.  Tried the same with XML file. But uploaded xml file is not found in "tcexam" directory.

**Comment by MubarakSaad9** [comment]
I hope this will help any one searching for a way to do it right
copy the example below and save it as TSV then import it as TSV

S=SUBJECT	subject_enabled	subject_name	subject_description
Q=QUESTION	question_enabled	question_description	question_explanation	question_type	question_difficulty	question_position	question_timer	question_fullscreen	question_inline_answers	question_auto_next
A=ANSWER	answer_enabled	answer_description	answer_explanation	answer_isright	answer_position	answer_keyboard_key

M	1	your course
S	1	block 1	
Q	1	This is where you but question ?		S	1		0	0	0	0
A	1	Correct answer		1		
A	1	Wrong answer1		0		
A	1	Wrong answer2		0		
A	1	Wrong answer3		0
Q	1	This is where you but question2 ?		S	1		0	0	0	0
A	1	Correct answer.		1		
A	1	Wrong answer1.		0		
A	1	Wrong answer2.		0		
A	1	Wrong answer3.		0
