### ISSUE TITLE
Error when uploading mp3 files - TCExam 12.1.30

### ISSUE THREAD

**Issue by diegospano** [tecnickcom/tcexam#106]
Hi. I just need to upload mp3 files but every time I do it I receive an error message saying that it was  unable to send the file. I checked folder permissions and everything is OK. Even more, I can create folders inside "cache" root folder, but I can´t upload any mp3 files. It is not a file size problem, files are very small.

What can I do?

Thanks in advance.

Diego

**Comment by nicolaasuni** [comment]
Be sure you are using the latest TCExam version and check the value of the K_ALLOWED_UPLOAD_EXTENSIONS constant in admin/config/tce_config.php file

**Comment by infohtreasure** [comment]
Try and give the folder read/write access ....

On Thu, Apr 9, 2015 at 7:12 AM, Nicola Asuni <notifications@github.com>
wrote:

> Be sure you are using the latest TCExam version and check the value of the
> K_ALLOWED_UPLOAD_EXTENSIONS constant in admin/config/tce_config.php file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/106#issuecomment-91259994>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*

**Comment by diegospano** [comment]
It ok now. It was  related with K_ALLOWED_UPLOAD_EXTENSIONS. Thanks a lot.

Diego
