### ISSUE TITLE
A little suggestion about question menu.

### ISSUE THREAD

**Issue by mathsong** [tecnickcom/tcexam#107]
Firstly, many thanks for your nice work!
Secondly, a little suggestion after two-week trial: if there are many questions (e.g. 40) the question menu would be too long; meanwhile aids on navigation is also wanted in this situation. 
One possible solution might be a setting in CSS, like 
{
	height: 130px; // define the height of question menu box
	overflow: auto; // when overflow, a scroll bar added automatically
} 

P.S. I don't know the exact place to post this thread, so I coming here..

**Comment by infohtreasure** [comment]
Please make your complaint with sample picture as i'm not able to reproduce
your question.

Thanks

On Mon, Apr 13, 2015 at 2:55 PM, mathsong <notifications@github.com> wrote:

> Firstly, many thanks for your nice work!
> Secondly, a little suggestion after two-week trial: if there are many
> questions (e.g. 40) the question menu would be too long; meanwhile aids on
> navigation is also wanted in this situation.
> One possible solution might be a setting in CSS, like
> {
> height: 130px; // define the height of question menu box
> overflow: auto; // when overflow, a scroll bar added automatically
> }
>
> P.S. I don't know the exact place to post this thread, so I coming here..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/107>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*

**Comment by mathsong** [comment]
It is just a small one: suppose you have 50 MCSA questions on a test and enable the "questions menu", you would say a long menu on every question page..

**Comment by infohtreasure** [comment]
that is tcexam default look

On Tue, Apr 14, 2015 at 2:07 AM, mathsong <notifications@github.com> wrote:

> It is just a small one: suppose you have 50 MCSA questions on a test and
> enable the "questions menu", you would say a long menu on every question
> page..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/107#issuecomment-92550141>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*
