### ISSUE TITLE
ERROR MESSAGE always appears

### ISSUE THREAD

**Issue by nismaty** [tecnickcom/tcexam#108]
hello,

TC exam works well, but with ERROR MESSAGE always appears:

ERREUR: [2] mysqli_query() expects parameter 1 to be mysqli, null given | LINE: 87 | FILE: C:\xampp\htdocs\TCExam\shared\code\tce_db_dal_mysqli.php

how can i solve this error ??

**Comment by infohtreasure** [comment]
Be sure you are using the latest version of TCEXAM

On Wed, Apr 15, 2015 at 4:07 PM, nismaty <notifications@github.com> wrote:

> hello,
>
> TC exam works well, but with ERROR MESSAGE always appears:
>
> ERREUR: [2] mysqli_query() expects parameter 1 to be mysqli, null given |
> LINE: 87 | FILE: C:\xampp\htdocs\TCExam\shared\code\tce_db_dal_mysqli.php
>
> how can i solve this error ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/108>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*
