### ISSUE TITLE
Help import users

### ISSUE THREAD

**Issue by mrmclaughlin** [tecnickcom/tcexam#110]
I have been trying to import users and have not had much success.  This is a sample I have been using to test but the field keep going in the wrong place.  Can you give me a sample tsv file to look at that does an import of several users...??

user_id	user_name	user_email	user_regdate	user_ip	user_firstname	user_lastname	user_birthdate	user_birthplace	user_regnumber	user_ssn	user_level	user_verifycode	user_otpkey	user_groups
 	username7	email2@email.com	1/1/2001	1:01:01	72.92.24.89	fname2	lname2	1/17/1997	birthplace2	1234	298642855	1	 	Students

**Comment by infohtreasure** [comment]
Add 1 or 2 user manually and export the TSV as your template, Open the tsv
file with MS-excel and populate it.


I hope that help

On Fri, Apr 24, 2015 at 4:42 PM, mrmclaughlin <notifications@github.com>
wrote:

> I have been trying to import users and have not had much success. This is
> a sample I have been using to test but the field keep going in the wrong
> place. Can you give me a sample tsv file to look at that does an import of
> several users...??
>
> user_id user_name user_email user_regdate user_ip user_firstname
> user_lastname user_birthdate user_birthplace user_regnumber user_ssn
> user_level user_verifycode user_otpkey user_groups
> username7 email2@email.com 1/1/2001 1:01:01 72.92.24.89 fname2 lname2
> 1/17/1997 birthplace2 1234 298642855 1 Students
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/110>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*
