### ISSUE TITLE
Pdf and UTF-8

### ISSUE THREAD

**Issue by NikitasMark** [tecnickcom/tcexam#112]
Hallo,

The pdf files, being produced from the results page, display Greek characters as questionmarks (?), even though I have set the DB to use UTF-8.

Is there a solution?

Thanks in advance

**Comment by nicolaasuni** [comment]
Yes, edit the shared/config/tce_pdf.php file and replace the default fonts with an Unicode font like dejavusans or freesans.

**Comment by NikitasMark** [comment]
Thank you very much. I' ll try it!
