### ISSUE TITLE
bruteforce false positive when works behind a NAT

### ISSUE THREAD

**Issue by peppelinux** [tecnickcom/tcexam#114]
https://github.com/peppelinux/tcexam/commit/3bcb8f39a8a9573c99bbc98961dc7b005d5149a1

When clients works behind a NAT the bruteforce detection should be deactivated.
It should be in config.php

**Comment by nicolaasuni** [comment]
you can set the K_BRUTE_FORCE_DELAY_RATIO constant to 0 in the shared/config/tce_config.php file
