### ISSUE TITLE
Ongoing German translation

### ISSUE THREAD

**Issue by c72578** [tecnickcom/tcexam#115]
This is just a note, that I am currently working on the German translation of TCExam.
Will be closed, when finished.

**Comment by c72578** [comment]
The first German translation update can be found here:
https://github.com/c72578/tcexam/commit/684ade923dbaf12b4870609f5c65bf1cc4accee1?diff=split

**Comment by infohtreasure** [comment]
Good job ......

On Wed, Jun 17, 2015 at 11:26 AM, Wolfgang Stöggl <notifications@github.com>
wrote:

> The first German translation update can be found here:
> c72578@684ade9?diff=split
> <https://github.com/c72578/tcexam/commit/684ade923dbaf12b4870609f5c65bf1cc4accee1?diff=split>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/115#issuecomment-112747083>.
>



-- 
Ifeoluwa Opeyemi O.
*www.ifeoluwaopeyemi.com <http://www.ifeoluwaopeyemi.com>*

Hidden Treasure Computers Limited
*RC894550*
www.htreasure.com
info.htreasure@gmail.com
*+234 803 9254 192*

**Comment by nicolaasuni** [comment]
merged, thanks.
