### ISSUE TITLE
<< Printing test answers and test at the same time >>

### ISSUE THREAD

**Issue by icamps** [tecnickcom/tcexam#119]
Hello,

I would like to know if it is possible to generate a PDF with the generated test together with its respective answers.

Regards,

Camps

**Comment by infohtreasure** [comment]
It is possible to generate a pdf of particular course or subject; questions along side with the answers

To do this go to list and select the appropriate course, un-check hide answers for you to see the answers and at the bottom of the page you can do any of the three.

1. PDF
2. PDF Course
3. PDF all

other options might not work if you  check, randomize questions and randomize answers but
i hope this solve answer your question in my understanding ?

Cheers.
