### ISSUE TITLE
Cannot Install TC Exam Please Help 

### ISSUE THREAD

**Issue by vickjoe** [tecnickcom/tcexam#120]
While trying to install Tc Exams i get this error message. Please help. 
![tcexam](https://cloud.githubusercontent.com/assets/6606039/9293037/2c7de3b2-4412-11e5-9701-b4a331cdc273.JPG)

**Comment by infohtreasure** [comment]
Make sure you supply the correct database username and password.

this should solve this error.

**Comment by nicolaasuni** [comment]
Wen installing TCExam you have to create the configuration folder.
Please follow the instructions at http://www.tcexam.org/installation.php
