### ISSUE TITLE
LaTeX Configuration 

### ISSUE THREAD

**Issue by abdulbasit2014** [tecnickcom/tcexam#121]
For configuring LaTeX, I have updated tce_latex.php. I have provided the absolute paths for images directory and executable files of pdflatex and imageMagic. You can have a look on tce_latex.php file below. 
But still I am unable to configure since use of Latex tag giving me "Latex Error"
Can someone explain the issue and its solution? Am I missing something ?

//============================================================+
// START OF FILE
//============================================================+
------------------------------------------------------------
*/

/**
 * Includes paths configuration file. */

require_once('../../shared/config/tce_paths.php');

/** * Absolute path to images directory. */

define ('K_LATEX_PATH_PICTURE', 'D:/Xampp_Installation/htdocs/tcexam/cache');

/**  * relative path to images directory. */

define ('K_LATEX_PATH_PICTURE_HTTPD', K_PATH_URL_CACHE);

/** * Path to PDFLATEX (/usr/bin/pdflatex).  */

define ('K_LATEX_PDFLATEX', 'D:/MixTeX Distribution/miktex/bin/pdflatex');

/**  * Path to ImageMagick convert (/usr/bin/convert). */

define ('K_LATEX_PATH_CONVERT', 'C:/Program Files/ImageMagick-6.9.2-Q16/convert');

/**  * Formula density used by ImageMagick (120).  */

define ('K_LATEX_FORMULA_DENSITY', 120);

/**  * Image width limit in pixels (500).  */

define ('K_LATEX_MAX_WIDTH', 800);

/**  * Image height limit in pixels (500). */

define ('K_LATEX_MAX_HEIGHT', 800);

/**  * Size limit for input string (500).  */

define ('K_LATEX_MAX_LENGHT', 500);

/** * Font size (10).  */

define ('K_LATEX_FONT_SIZE', 10);

/**  * LaTeX class (article). */

define ('K_LATEX_CLASS', 'article');

/** * Filename prefix for chached images (latex_). */

define ('K_LATEX_IMG_PREFIX', 'latex_');

/** * Image format (png). */

define ('K_LATEX_IMG_FORMAT', 'png');

//============================================================+
// END OF FILE
//============================================================+

**Comment by nicolaasuni** [comment]
Please check the following document to debug the LaTeX settings:
https://github.com/tecnickcom/tcexam/blob/master/LATEX_README.TXT

**Comment by mazydah** [comment]
hello,
 please how can i install latex on a shared hosting platform. i am running tcexam on the web.

thanks
