### ISSUE TITLE
Cannot install TCExam in ubuntu using xampp 5.6.11

### ISSUE THREAD

**Issue by devnath** [tecnickcom/tcexam#122]
Hello all,
I am a new user here.
Cannot install TCExam in ubuntu using xampp 5.6.11 ?
Can anyone please upload some step-by-step snapshots or video to be able to install TCExam in Ubuntu
using xampp 5.6.11 ?

 Please Help
Thanks in advance.

**Comment by infohtreasure** [comment]
Why use xampp ?

Install LAMP on your ubuntu server and follow instructions at TCexam installation page to install other packages.

Pretty straight forward.

Cheers

**Comment by nicolaasuni** [comment]
Please follow this guide to install TCExam:
http://www.tcexam.org/installation.php
