### ISSUE TITLE
ERROR MESSAGE: AFTER CLICKING ON GENERATE PDF OFFLINE TEST BUTTON

### ISSUE THREAD

**Issue by tuny4me** [tecnickcom/tcexam#123]
hello 
i get this error when i click on the generate button in pdf offline test 
ATTENTION: [8] Undefined offset: 0 | LINE: 770 | FILE: C:\wamp\www\frsconlineexam\admin\code\tce_pdf_testgen.php
TCPDF ERROR: Some data has already been output, can't send PDF file

**Comment by infohtreasure** [comment]
I use to see this error long time ago but how i solve it ?
for me it's always folder permission issue and file permission issues

after changing my folder rights (cache folder, image folder'i have another folder for other images here')

the error msg disappear.

you and try this but not sure this is the best way to solve resolve it.

cheers

**Comment by nicolaasuni** [comment]
Your system is probably generating an error message that is sent before the PDF data.
Please check if you are following the instructions here:
http://www.tcexam.org/installation.php
