### ISSUE TITLE
How to read OMR answer sheet in TCExam opensource

### ISSUE THREAD

**Issue by lakshmanaraog** [tecnickcom/tcexam#124]
How to read OMR answer sheet in TCExam opensource?
I am using windows 7 operating system and i downloaded TCExam opensource. Installed TCExam and zbarimg. Configured the zbarimg in config file like below:
define ('K_OMR_PATH_ZBARIMG', 'C:/Program Files (x86)/ZBar/bin');
After login in admin section, tests -> Import Answers (OMR) link, selected OMR DATA and OMR ANSWER SHEET 1 JPG images and click on send button.
After that i got below error:
ERROR: the image of OMR DATA page is missing or unreadable

Please let me know how to fix the issue and read the OMR ANSWER SHEET.

**Comment by infohtreasure** [comment]
When scanning your OMR DATA page how deep is your scanning Try you 200DPI to scan and see if this will solve your issue.Have not encounter this error before, I use linux as my base Os.Regards                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10............Ifeoluwa Opeyemi O.www.ifeoluwaopeyemi.comHidden Treasure Computers LimitedRC894550www.htreasure.cominfo.htreasure@gmail.com+234 803 9254 192                                                                                                                                                                                                                From: lakshmanaraogSent: Wednesday, September 23, 2015 7:31 AMTo: tecnickcom/tcexamReply To: tecnickcom/tcexamSubject: [tcexam] How to read OMR answer sheet in TCExam opensource (#124)How to read OMR answer sheet in TCExam opensource?
I am using windows 7 operating system and installed TCExam and zbarimg. Configured the zbarimg in config file like below:
define ('K_OMR_PATH_ZBARIMG', 'C:/Program Files (x86)/ZBar/bin');
After login in admin section, tests -> Import Answers (OMR) link, selected OMR DATA and OMR ANSWER SHEET 1 JPG images and click on send button.
After that i got below error:
ERROR: the image of OMR DATA page is missing or unreadable

Please let me know how to fix the issue and read the OMR ANSWER SHEET.

—Reply to this email directly or view it on GitHub.

**Comment by lakshmanaraog** [comment]
I converted the 200dpi to OMR DATA and OMR ANSWER SHEET 1 also but i am getting the same issue.
ERROR: the image of OMR DATA page is missing or unreadable

Find the attached images and let me know any thing wrong with the image / file name / etc...


![omr 1001 _a 1](https://cloud.githubusercontent.com/assets/14799778/10041373/7be8ab82-6201-11e5-86fe-c90e680c524a.png)
![omr_ 1001 qr](https://cloud.githubusercontent.com/assets/14799778/10041404/93185154-6201-11e5-93c2-ce9d19d0345c.png)

**Comment by lakshmanaraog** [comment]
Anyone please reply to fix the issue. Is anything wrong i did or any thing need to configure or add to TCExam to read the OMR DATA and OMR ANSWER SHEET.

**Comment by infohtreasure** [comment]
I have downloaded both image can you upload your questions and answers let me see if i can reproduce it on my machine.

and another thing that i noticed is the size of your scanned image it's small here a copy of my to compare.

scan in  A4 paper size.

![3](https://cloud.githubusercontent.com/assets/8158809/10043174/be0f1866-61e8-11e5-90ea-71da0c5258fa.jpg)
![3aa](https://cloud.githubusercontent.com/assets/8158809/10043234/31e7401a-61e9-11e5-9515-fc3f1fa0cfe3.jpg)

**Comment by infohtreasure** [comment]
One more thing, i have QR scanner on my phone, I’m able to scan your  OMR answer sheet but was not able to scan your DATA SHEET.

Try increase your scan size.

Hope you'll have joy...

**Comment by lakshmanaraog** [comment]
Thanks for replying and i took the scanned page with 200dpi and i uploaded the same to under Import Answers (OMR) page. After click on "send" it is not showing any result.

While displaying the zbarimg command, it shows below
"C:/Program Files (x86)/ZBar/bin/zbarimg" --raw -Sdisable -Sqrcode.enable -q "OMR_[1001]QR.png"

Is anything wrong in the command and there is no path for OMR DATA file. Please let me know how to fix it.

**Comment by lakshmanaraog** [comment]
Anyone please reply to fix the issue.

**Comment by nicolaasuni** [comment]
Depending on your settings, sometimes the image processing parameters needs some tuning.
It is difficult to say what is wrong without having the original scanned images.

**Comment by lakshmanaraog** [comment]
I am just scanning the OMR QR code using below command

"C:/Program Files (x86)/ZBar/bin/zbarimg" --raw -Sdisable -Sqrcode.enable -q "OMR_[1001]QR.png"

This is givin by TCExam only. I just modified the zbarimg path. Is this command is right or not.
I am not getting any result after executing the command.

**Comment by phong999** [comment]
Very good

**Comment by nicolaasuni** [comment]
Close for lack of activity.
