### ISSUE TITLE
Cannot log in to TCExam using IE

### ISSUE THREAD

**Issue by pathum83** [tecnickcom/tcexam#125]
Hi

Once user name & password entered, system is not proceed to next screen. However login is fine with Chrome. Only issue with the internet explore.

Pls help on this.

Rgds
Pathum

**Comment by nicolaasuni** [comment]
Please check if you are blocking cookies or you are using any "security" tool in IE that may interfere with cookies.

**Comment by pathum83** [comment]
Hi

Thanks.

Cookies are enabled. 

![image](https://cloud.githubusercontent.com/assets/14833090/10096891/cf9a8f88-6392-11e5-8255-53f8b4785524.png)

Any other settings that needs to pay attention?

**Comment by pathum83** [comment]
Hi

It's working after restart the server.

Don't know what has happened.

Any way thanks for the promt responses.

Rgds
Pathum
