### ISSUE TITLE
<<  Question Order in PDF >>

### ISSUE THREAD

**Issue by icamps** [tecnickcom/tcexam#126]
Hello,

My question is related to issue #58.

I only use (now) TCExam to generate PDF tests.

My questions are introduced by topics and with different degree of difficulty.

When generating the tests, I want to retain the order of the topics I used when adding the questions to a given test.

As I select "random questions", the test are produced ok, but with the questions out of order. If I deselect the first option, and select "order" and put "Topics" in order by, the test produced have the questions ordered by the topic the questions were added to the test but are all the same (I have more than 5 questions in each topic).

As I read in the file "tce_pdf_testgen.php", all the test generated in PDF, have they answers in random mode.

Regards,

Camps

**Comment by nicolaasuni** [comment]
Currently the PDF are always generated in random order.
This makes sense, as you want to minimize the chances of cheating.

**Comment by icamps** [comment]
Thanks Nicola,

This is of course a very good feature. I was wondering if the order of topics can be fixed, not the order of questions inside each topic.

Regards

**Comment by nicolaasuni** [comment]
Currently only the questions can be ordered, the topics are always random.
