### ISSUE TITLE
tc exam installtion error  on wamp

### ISSUE THREAD

**Issue by thaez** [tecnickcom/tcexam#127]
i have been trying to install tc exam with wamp, i dont really know what am not getting right because i keep getting this error...kindly help me out
![untitled](https://cloud.githubusercontent.com/assets/13392775/10433425/ad6f9bc2-7109-11e5-8b92-96e29ccf4abf.jpg)

start TCExam installation............[OK]
start database installation.........[OK]
create or replace database and get connection........[OK]
create database tables.......... 
( ! ) Fatal error: Maximum execution time of 120 seconds exceeded in C:\wamp\www\tcexam-master\shared\code\tce_db_dal_mysqli.php on line 87
Call Stack
#	Time	Memory	Function	Location
1	0.0010	316256	{main}( )	..\install.php:0
2	0.0020	407192	F_install_database( )	..\install.php:85
3	14.5138	436784	F_execute_sql_queries( )	..\tce_functions_install.php:68
4	113.1155	486272	F_db_query( )	..\tce_functions_install.php:129

**Comment by nicolaasuni** [comment]
Please check the answer:
https://github.com/tecnickcom/tcexam/issues/128
