### ISSUE TITLE
tc exam installtion error  on wamp

### ISSUE THREAD

**Issue by thaez** [tecnickcom/tcexam#128]
i get the error below while trying to install tc exam, kindly help cause i dont know what am not getting right. below is the screenshot...kindly help me out, am using window 7
![untitled](https://cloud.githubusercontent.com/assets/13392775/10433588/0d533ee4-710b-11e5-98de-5ff17ce1de2b.jpg)

**Comment by nicolaasuni** [comment]
Please check if the database is correctly installed or try to manually install TCExam following the guide at: http://www.tcexam.org/installation.php
