### ISSUE TITLE
Invalid licensing

### ISSUE THREAD

**Issue by JaapJoris** [tecnickcom/tcexam#129]
The file `LICENSE.TXT`opens with the following statement: "TCEXAM IS SUBJECT TO THE FOLLOWING GNU-AGPLV3 LICENSE ONLY FOR NON-COMMERCIAL USAGE."

This is not possible. You cannot release something under the GPL for non-commercial use only. That is an invalid additional restriction which the GPL forbids. This means you either just revoked the GPL in the very sentence you granted it, making everyone legally unable to use your product without a commercial license, or you just granted everyone the right to use it commercially as well.

This is also adressed in the [GPL FAQ](http://www.gnu.org/licenses/gpl-faq.html#NoMilitary):

> I'd like to license my code under the GPL, but I'd also like to make it clear that it can't be used | for military and/or commercial uses. Can I do this?
> No, because those two goals contradict each other. The GNU GPL is designed specifically to prevent the addition of further restrictions. GPLv3 allows a very limited set of them, in section 7, but *any other added restriction can be removed by the user*.

**Comment by nicolaasuni** [comment]
Thank you for pointing out this issue. I have just updated the licensing terms to be more clear.
