### ISSUE TITLE
PDF generation error on line 44 of tcpdfex.php

### ISSUE THREAD

**Issue by nicoledaniel3** [tecnickcom/tcexam#130]
Whenever I try to generate a PDF of my test for use offline, I get the same error on line 44 of tcpdfex.php. The error message is below. I got the same error when I tried to generate a PDF using any button: either from the module screen or from the test itself. How can I fix this error?

ERROR: [2] require(C:\wamp\www\tcexam\shared\code/../tcpdf/tcpdf.php): failed to open stream: No such file or directory | LINE: 44 | FILE: C:\wamp\www\tcexam\shared\code\tcpdfex.php

( ! ) Fatal error: require(): Failed opening required 'C:\wamp\www\tcexam\shared\code/../tcpdf/tcpdf.php' (include_path='.;C:\php\pear') in C:\wamp\www\tcexam\shared\code\tcpdfex.php on line 44
Call Stack
#	Time	Memory	Function	Location
1	0.0109	300032	{main}( )	..\tce_pdf_testgen.php:0
2	0.1090	1472504	require_once( 'C:\wamp\www\tcexam\shared\code\tcpdfex.php' )	..\tce_pdf_testgen.php:38

**Comment by nicolaasuni** [comment]
Seems a problem related to mixed back and forward slashes in the paths.
Please check the configuration files and switch to Linux if possible.
