### ISSUE TITLE
How to insert non-breaking space characters

### ISSUE THREAD

**Issue by c72578** [tecnickcom/tcexam#132]
What would be the recommended way to insert non-breaking space characters into the text of questions and answers of TCExam?
Environment: Windows 7, Browser: Firefox 42

Non-breaking space characters should be inserted, as described here:
https://en.wikipedia.org/wiki/Non-breaking_space

Text example:
Inside this line there is a number and a unit like 400 m and the space character should be non breaking between 400 and m.

**Comment by nicolaasuni** [comment]
In Windows you should be able to type the Unicode Character 'NO-BREAK SPACE' (U+00A0) using one of these sequences:

Alt +00A0
Alt 0160
Alt 255

**Comment by c72578** [comment]
Thanks for your answer.
So far I  could try Alt+0160 and Alt+255.
Unfortunately without success. The generated offline PDF Test still breaks the lines between number and unit.
