### ISSUE TITLE
Users not able to perform some task while giving exam

### ISSUE THREAD

**Issue by Gitanjali86** [tecnickcom/tcexam#133]
While giving exam users is not able to following task:-

1. Users not able to click on "Previous" button
2. Users has not read complete question and it goes to next question automatically ( I din't set any timer too)
3. At the last question, it keeps on refreshing on last question only.

lease help me at the earliest on these doubts?
I need guidance on these.

**Comment by nicolaasuni** [comment]
check if the "automatic next" in the question editor is correctly unset and the "questions menu" in the test editor is set.

**Comment by Gitanjali86** [comment]
Thanks for reply nicolaasuni.

"automatic next" - is not set
"question menu" - I want to keep it unset as I don't want question menu to show up.

So still issue persist for all 3.
