### ISSUE TITLE
Tests not appearing after student signin

### ISSUE THREAD

**Issue by mbacourse** [tecnickcom/tcexam#134]
I have created group, module, topic and later created test and associated to group 2, 
but when student sign in, the index tab is empty, though the assigned group has test.

Accidently, I have deleted default group, is this causing this issue.

Any help highly appreciated.

**Comment by nicolaasuni** [comment]
Tests only appears to enabled students.
Please check the following guide:
http://www.tcexam.org/guide_first_test.php

**Comment by mbacourse** [comment]
Thank you,  I was able to figure out after trial and error, but I have
another question, how can i create dependency between tests, like take
test2 only test 1 is either pass or about 75%.

cheli
