### ISSUE TITLE
require_once(../config/tce_config.php): failed to open stream:

### ISSUE THREAD

**Issue by donejeh** [tecnickcom/tcexam#135]
Hi i need help please am having problem installing the script..

Warning: require_once(../config/tce_config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\CBT\admin\code\index.php on line 34

Fatal error: require_once(): Failed opening required '../config/tce_config.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\CBT\admin\code\index.php on line 34

it could not found the config dir any help?

**Comment by nicolaasuni** [comment]
Please check the installation instructions at http://www.tcexam.org
Seems that you have forgotten to copy and edit the configuration files.
