### ISSUE TITLE
Issue with user sign-on

### ISSUE THREAD

**Issue by PageTown** [tecnickcom/tcexam#136]
When a non-admin level user signs-on to TCExam, the screen remains on the log in page rather than landing on the tests page which is where I assume it is supposed to land. I have attached an image of what I am seeing after logging in. 

I have created a group called "Students" and added the user to that group. I've also set their level to '1". 

I can get to the tests by clicking on the "public" tab, but it would be nice to have the user land there automatically after logging in.

![error](https://cloud.githubusercontent.com/assets/11357194/11639549/19f0d90e-9cf3-11e5-8a90-a06498dbab74.jpg)

**Comment by nicolaasuni** [comment]
I am unable to reproduce this issue.
Please try to upgrade to the latest version and report what Web browser are you using.

**Comment by PageTown** [comment]
I am using TC Exam version 12.2.6 

I have tried using Chrome and Firefox and both do the same thing.

**Comment by nicolaasuni** [comment]
Please check if the non-admin users have at least a level of 1 and they are trying to log to the public area and not the administrative one.

**Comment by likewwddaa** [comment]
I met the same problem.

**Comment by damms005** [comment]
@nicolaasuni It also happens intermittently with me. It is not easily unrerproduceable. Something is definitely unstable with the routing/forwarding logic after auth.
