### ISSUE TITLE
Latex escape character not working

### ISSUE THREAD

**Issue by teaborn** [tecnickcom/tcexam#137]
If it try to write a simple text in LaTeX i got the following error:
[LaTeX: ERROR invalid command]

[tex]
\begin{document}
neigbor %loop
\end{document}
[/tex]

Everytime i use special internal LaTeX command like: loop, def or command i got this error. Escape character "\" ist not working

**Comment by nicolaasuni** [comment]
Please follow the instructions in the LATEX_README.TXT fiel to debug the LaTeX converter.
