### ISSUE TITLE
creating a database

### ISSUE THREAD

**Issue by theyogre** [tecnickcom/tcexam#138]
I'm looking to create a database of test questions that can be used for an open educational resource project (with Chemwiki). To be useful for a wide range of educators, the database needs to be sortable in many different ways. I know things can be organized according to topic, type of problem, difficulty, and a couple of other things, but I would also like to be able to organize them in other ways. I would like to be able to identify things like number of computational steps, appropriateness for different courses with overlapping content, multiple topics, Bloom's taxonomy, or other things I haven't thought of yet. Is the database flexible enough to handle such a variety of sortings already? Could it be made more flexible by a programmer with database experience without harming the already established core functionality?

I'm trying to select the platform for this OER project so that I can spend my efforts as effectively as possible, and I would love help from someone knowledgeable who can answer questions like these. Thanks in advance for any guidance.

**Comment by nicolaasuni** [comment]
On 06/01/16 21:24, theyogre wrote:
> I'm looking to create a database of test questions that can be used for
> an open educational resource project (with Chemwiki) To be useful for a
> wide range of educators, the database needs to be sortable in many
> different ways I know things can be organized according to topic, type
> of problem, difficulty, and a couple of other things, but I would also
> like to be able to organize them in other ways I would like to be able
> to identify things like number of computational steps, appropriateness
> for different courses with overlapping content, multiple topics, Bloom's
> taxonomy, or other things I haven't thought of yet Is the database
> flexible enough to handle such a variety of sortings already? Could it
> be made more flexible by a programmer with database experience without
> harming the already established core functionality?

You can always write an inport module for TCExam to import/export the
questions.

> 
> I'm trying to select the platform for this OER project so that I can
> spend my efforts as effectively as possible, and I would love help from
> someone knowledgeable who can answer questions like these Thanks in
> advance for any guidance
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecnickcom/tcexam/issues/138>.
> 


-- 

Nicola Asuni

Tecnick.com Limited
info@tecnick.com
http://www.tecnick.com

**Comment by theyogre** [comment]
That's partly helpful. Thank you. Would it require that I have a separate database than the structure that is already in place? Instructors would then select questions using an interface with the separate database, and then import them to TCExam for use? While not an ideal solution, it could work. 

Does the current database handle tags for questions? Could I just make a standard list of tags for my users?

If I learned the database programming language (or found someone who knows it) could I submit an extension or patch for the existing database that would do what I want, instead of building a separate database?

**Comment by nicolaasuni** [comment]
You can always submit patches and suggestions.
