### ISSUE TITLE
Programming a Database

### ISSUE THREAD

**Issue by theyogre** [tecnickcom/tcexam#139]
If I want to program a module that will generate or reformat test questions from other sources to be entered into a TCExam database, is there a particular programming language I should use/learn that would be most compatible with the existing structures?

**Comment by nicolaasuni** [comment]
You can edit the admin/code/tce_import_custom.php fiel to look like the tce_class_import_xml.php but with your custom importing rules.
Then you can enable this module from the configuration file admin/config/tce_config.php :
define ('K_ENABLE_CUSTOM_IMPORT', '');
