### ISSUE TITLE
TCExam Multiple Choice Problem (Question is showing wrong number of options, say double)

### ISSUE THREAD

**Issue by nitin-t** [tecnickcom/tcexam#142]
While conducting exam every question is getting double answers for example, if 4 options are there it is showing 8 options.
Q1. Where is Sun?
1. A
2. B
3. C
4. D
5. E
6. F
7. G
8. H
NOTE: Module has only 4 options for each question.

Kindly help in this
Thanks in advance

**Comment by infohtreasure** [comment]
i want to believe that this is where you select 8options

see attached photo
![qwe](https://cloud.githubusercontent.com/assets/8158809/13314214/3cc7e16c-dba4-11e5-87e1-79a504352e3d.png)

**Comment by infohtreasure** [comment]
Number of answers ........

**Comment by nitin-t** [comment]
Thanks for reply, I have checked, it is 4 (number of answers), but it is showing 8 answers, extra 4 answers from other question.

**Comment by nicolaasuni** [comment]
I have recently updated TCExam to 13.1.1. Please update and let me know it this fixes your issue.
