### ISSUE TITLE
Multiple Choice Multiple Answer not working: no answers selected

### ISSUE THREAD

**Issue by RoelandLengers** [tecnickcom/tcexam#144]
I'm using the latest version of TCExam. According to the CHANGELOG.TXT this is 13.0.1 (2015-12-12).

I've set up a simple test with two questions:
1: Multiple Choice, Single Answer. Simple TRUE or FALSE.
2: Multiple Choice, Multiple Answer. Five answers: Correct1, Correct2, Incorrect1, Incorrect2, Incorrect3

The questions and answers show up correct when executing the test. However, when answering the MCMA question, the selected answers are not taken in by the server. I can see that the POST does send  the information to the server:

> <snip>
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="answpos[1]"
> 
> 1
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="answpos[2]"
> 
> 0
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="answpos[3]"
> 
> 0
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="answpos[4]"
> 
> 1
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="answpos[5]"
> 
> 0
> ------WebKitFormBoundarya3EoEXSIjuM9WKjq
> Content-Disposition: form-data; name="confirmanswer"
> 
> </snip>

However, when the screen refreshes, none of the selected options are stored:

<img width="576" alt="screen shot 2016-03-15 at 12 25 04" src="https://cloud.githubusercontent.com/assets/9610733/13776167/ff38ba88-eaa8-11e5-90fa-dbc92ce67dec.png">
Hit confirm:
<img width="571" alt="screen shot 2016-03-15 at 12 25 47" src="https://cloud.githubusercontent.com/assets/9610733/13776182/15a91c04-eaa9-11e5-990e-a442651118c8.png">

I've tried using "Partial score" for MCMA, and used Both "Radiobuttons for MCMA" on and off. Doesn't matter.

What goes wrong here?

I love TCExam, but this is severely limiting its usefulness. 

Thanks!

**Comment by nicolaasuni** [comment]
OK. It was a bug introduce with 13.0.0 version.
It has now been fixed in 13.1.0.
