### ISSUE TITLE
Creating user test under <tests> not working

### ISSUE THREAD

**Issue by samarita** [tecnickcom/tcexam#147]
Hello,
I have mentioned this before, but I don't believe there has been a solution:

1. Click on tests
2. Click on users
3. Select test, select user
4. Click on PDF
Error message:

Fatal error: Maximum execution time of 90 seconds exceeded in /home/xxxxx/public_html/xxxxx/shared/tcpdf/include/tcpdf_fonts.php on line 1843

**ATTENTION: [8] Undefined index: '618' | LINE: 248 | FILE: /home/xxxxxxx/public_html/xxxxxxx/admin/code/tce_pdf_results.php
TCPDF ERROR: Some data has already been output, can't send PDF file**

I am using version 13.1.1.

Regards,

**Comment by nicolaasuni** [comment]
The system is probably outputting some error that you can't see because you are in PDF mode.
Please enable full PHP logs and set the error reporting level to maximum so you can identify what is the issue. It can be a misconfigured path or a missing dependency,
