### ISSUE TITLE
Error showing up in latest version  13.1.1 (2016-03-15)

### ISSUE THREAD

**Issue by Gitanjali86** [tecnickcom/tcexam#149]
Hi Nicolaasuni,

I have seen a different error (in latest version 13.1.1 (2016-03-15)) which show up on sending email, DB installation and few more.
This is unlike old version.
Pls find the attached screenshot as I am unable to remove this.

please put some light on this.

[Error screenshot.docx](https://github.com/tecnickcom/tcexam/files/215712/Error.screenshot.docx)

**Comment by nicolaasuni** [comment]
This should be fixed in TCExam 13.2.0.
