### ISSUE TITLE
how to download the pdf for offline test

### ISSUE THREAD

**Issue by arpanparutang** [tecnickcom/tcexam#150]
dear all
i always fail when ganerate a pdf test for offline user,i use xampp with apache as a server ..can anyone help me ?

**Comment by nicolaasuni** [comment]
Please enable the maximum reporting level for php and log the errors to debug what is the issue.

**Comment by arpanparutang** [comment]
forgive me..but i don't know how to enable the reporting level for php
become maximum..can you help me pls..?

2016-08-22 2:18 GMT+07:00 Nicola Asuni <notifications@github.com>:
