### ISSUE TITLE
Warning: require_once(../config/tce_config.php)

### ISSUE THREAD

**Issue by syedbaqarrizvi** [tecnickcom/tcexam#156]
I am trying to install it at my Lampp base Ubantu and having that error ,

Warning: require_once(../config/tce_config.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/tcexam-develop/public/code/index.php on line 34

Many Thanks,

**Comment by nicolaasuni** [comment]
Seems that you haven't created the config folders. Please read:
https://tcexam.org/docs/installation/
