### ISSUE TITLE
Fatal error-

### ISSUE THREAD

**Issue by syedbaqarrizvi** [tecnickcom/tcexam#157]
Hello nicolaasuni,
 
I have installed it was fine i am confused why it is showing it abut statement error ,

Fatal error: Switch statements may only contain one default clause in /opt/lampp/htdocs/tcexam-develop/shared/code/tce_db_dal.php on line 51

Many Thanks ,
Baqarrizvi

![image](https://cloud.githubusercontent.com/assets/15075559/17854151/fdd30d24-6889-11e6-9c6d-64d4de536939.png)

**Comment by nicolaasuni** [comment]
Fixed in TCExam 13.2.1.
Thanks.
