### ISSUE TITLE
Bug found in tce_test_execute.php

### ISSUE THREAD

**Issue by masfu** [tecnickcom/tcexam#158]
we could not believe that all of our student got perfect score of all test and we investigate we found this trick. while student do their test, they could find the correct answer from the value of radio button input for example
```
<input type="radio" name="answerid" id="answerid_72" value="72">
<input type="radio" name="answerid" id="answerid_71" value="71">
<input type="radio" name="answerid" id="answerid_73" value="73">
<input type="radio" name="answerid" id="answerid_74" value="74">
```
the answer is 71 or the minimum value. i don't know why could be happen. finally we decide to disable  right click using javascript but for advance student they could open developer tool from browser setting

**Comment by nicolaasuni** [comment]
Seems that you are using an old TCExam version, please upgrade.

**Comment by masfu** [comment]
ok thanks
