### ISSUE TITLE
Use of undefined constant K_USRREG_PASSWORD_RE

### ISSUE THREAD

**Issue by ilias-ec** [tecnickcom/tcexam#159]
Before few minutes (Sunday 4/9/2016 - 23:30 - Greek time) i install the tcexam ver. 13.2.1
I try to change the admin password and on screen appears, before select admin user and type anything, a green message:
ATTENTION: [8] Use of undefined constant K_USRREG_PASSWORD_RE - assumed 'K_USRREG_PASSWORD_RE' | LINE: 453 | FILE: /var/www/html/tcexam/admin/code/tce_edit_user.php
Please tell me whats going wrong....

Best Regards,
Elias

**Comment by nicolaasuni** [comment]
You are probably upgrading from a previous version as this constant was added in the latest version. Please check the commit diff here.

**Comment by ilias-ec** [comment]
Thanks for your answer.
But i start from 0. No previous version.

**Comment by nicolaasuni** [comment]
In which page are you getting this error?

**Comment by nicolaasuni** [comment]
I have found the issue, I should be able to commit a fix in less than one hour.

**Comment by nicolaasuni** [comment]
Fixed in TCExam 13.3.0.
Thank you for reporting this issue.

**Comment by ilias-ec** [comment]
It's OK.
Thanks a lot.
