### ISSUE TITLE
default user and password

### ISSUE THREAD

**Issue by eloelo22** [tecnickcom/tcexam#160]
i installed tcexam just about a minute ago according to the documents the default username is admin password is 1234 i tried to login from the admin page but it's being rejected i opened the table tce_users and it's blank now of course i can create manually the user but i don't know the user level for an administrator 

help please

thank you
![capture](https://cloud.githubusercontent.com/assets/8648535/18573923/9da76d1c-7bfa-11e6-9c1c-3ea044173838.PNG)

**Comment by andrearicci** [comment]
same problem here.
Please help,
Thank you

**Comment by aamirbekov** [comment]
I am also have the same problem
I have aded recodrs below in tables tce_users and tce_usrgroup
tce_users:
id     user_name    user_password     user_regdate                     user_ip       user_level
3	almas	     12345678		2001-01-01 01:01:01	0.0.0.0	  10	

tce_usrgroup:
usrgrp_user_id     usrgrp_group_id
3                         1

but still can't login

**Comment by aamirbekov** [comment]
Just now i have logged in with firefox.
with Chrome still I can't log in.
I asked colleagues try to login with Chrome. Nobody could. 
I think Chrome or  TCexam has some problem with each other

**Comment by nicolaasuni** [comment]
Please do not comment on old closed issues.
Be sure you are using the latest TCExam version and following the official installation guide on https://tcexam.org

**Comment by 949262** [comment]
i installed tcexam  according to the documents the default username is admin password is 1234 i tried to login from the admin page but it's being rejected shows error msg ATTENTION: wrong user / password

help please

thank you
capture

**Comment by araya10** [comment]
I am also have the same problem installed tcexam according to the documents the default username is admin password is 1234 i tried to login from the admin page but it's being rejected shows error msg ATTENTION: wrong user / password

**Comment by asiflinux786** [comment]
hi i am facing the same problem could not login in to tcexam server

**Comment by asiflinux786** [comment]
can anyone help me i want to reinstall on ubutu 22.04 as i am facing the login issue any one can help me send me detials on asiflinux786@gmail.com
