### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kinsomicrote** [tecnickcom/tcexam#161]
This is the error I get when installing TCExam.

```
start TCExam installation............[OK]
start database installation.........[OK]
create or replace database and get connection........[OK]
create database tables.......... [OK]
fill tables with default data... [OK]
end database installation...........[OK]
start config files update...........[OK]
start process tce_db_config.php file:
open file.................[ERROR]
end process tce_db_config.php file
start process tce_paths.php file:
open file.................[ERROR]
end process tce_paths.php file
end config files update.............[OK]
end TCExam installation..............[OK]
```

I'm using LAMP stack on Ubuntu 16.04. Any solution?

**Comment by c72578** [comment]
This could be related to SELinux, preventing access to tce_db_config.php, tce_paths.php etc.

Check for possible SELinux alerts, e.g.:
SELinux is preventing httpd from write access on the file /var/www/html/tcexam/shared/config/tce_paths.php.
If you want to allow httpd to have write access on the tce_paths.php file
Then you need to change the label on '/var/www/html/tcexam/shared/config/tce_paths.php'
Do
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/tcexam/shared/config/tce_paths.php'
restorecon -v '/var/www/html/tcexam/shared/config/tce_paths.php'

**Comment by nicolaasuni** [comment]
Usually you have to create these files from the default config folder.
