### ISSUE TITLE
how Configuring Latex in TCExam in Windows Platform with XAMPP

### ISSUE THREAD

**Issue by tonisma12** [tecnickcom/tcexam#162]
the configuration that i change

*/

/**
- Includes paths configuration file.
  */
  require_once('../../shared/config/tce_paths.php');

/**
- Absolute path to images directory.
  */
  define('K_LATEX_PATH_PICTURE', K_PATH_CACHE);

/**
- relative path to images directory.
  */
  define('K_LATEX_PATH_PICTURE_HTTPD', K_PATH_URL_CACHE);

/**
- Path to LATEX (/usr/bin/latex).
  */
  define('K_LATEX_PATH_LATEX', 'C:/Progra~1/MiKTeX~2.9/miktex/bin/latex.exe');

/**
- Path to PDFLATEX (/usr/bin/pdflatex).
  */
  define('K_LATEX_PDFLATEX', 'C:/Progra~1/MiKTeX~2.9/miktex/bin/pdflatex.exe');

define ('K_LATEX_PATH_DVIPS', 'C:/Progra~1/MiKTeX~2.9/miktex/bin/dvips.exe');

/**
- Path to ImageMagick convert (/usr/bin/convert).
  */
  define('K_LATEX_PATH_CONVERT', 'C:/Progra~1/Imagem-7.0.3-Q16/convert.exe');

define ('K_LATEX_PATH_IDENTIFY', 'C:/Progra~1/Imagem-7.0.3-Q16/identify.exe');

/**
- Formula density used by ImageMagick (120).
  */
  define('K_LATEX_FORMULA_DENSITY', 120);

/**
- Image width limit in pixels (500).
  */
  define('K_LATEX_MAX_WIDTH', 800);

/**
- Image height limit in pixels (500).
  */
  define('K_LATEX_MAX_HEIGHT', 800);

/**
- Size limit for input string (500).
  */
  define('K_LATEX_MAX_LENGHT', 500);

/**
- Font size (10).
  */
  define('K_LATEX_FONT_SIZE', 10);

/**
- LaTeX class (article).
  */
  define('K_LATEX_CLASS', 'article');

/**
- Filename prefix for chached images (latex_).
  */
  define('K_LATEX_IMG_PREFIX', 'latex_');

/**
- Image format (png).
  */
  define('K_LATEX_IMG_FORMAT', 'png');

what is wrong, please help me.

**Comment by haneefputtur** [comment]
You can refer to my old article about this..
Its for an older version may help you.

http://haneefputtur.com/configuring-latex-in-tcexam-in-windows-platform-with-xampp.html
