### ISSUE TITLE
TCEXAM Multiple Admin

### ISSUE THREAD

**Issue by saiftornado** [tecnickcom/tcexam#163]
Dear sir / madam,

I would like to know if i can create multiple admins where one admin will not see the contents (modules, tests, users) of another admin.

Suppose admin1 has created a module m1 and test t1
but admin2 will not find m1 in module list and t1 in test list.

Regards,

Saiful Azad

**Comment by nicolaasuni** [comment]
Yes, on the user editor you can assign the modules administrators a level that is less than 10.
Then on the modules editor you can set the module owner.
