### ISSUE TITLE
PHP Fatal error:  Switch statements may only contain one default clause in /opt/tcexam-13.1.1/shared/code/tce_db_dal.php on line 51

### ISSUE THREAD

**Issue by doomsbuster** [tecnickcom/tcexam#167]
Receive the following error when running TC Exam 13.1.1 on PHP7 with Apache 2.4:

```
[Tue Dec 27 05:10:39.676076 2016] [:error] [pid 20558] [client 74.105.8.189:50015] PHP Fatal error:  Switch statements may only contain one default clause in /opt/tcexam-13.1.1/shared/code/tce_db_dal.php on line 51
```

The fix is to remove the duplicate defaults and keep just one default case.

**Comment by nicolaasuni** [comment]
Please upgrade to the latest version, it is fixed there already.

**Comment by oldnewbie95** [comment]
I'm sorry, but I dont get this. upgrade what and how? I still recieve the error message
