### ISSUE TITLE
Issue with Oracle :: tce_db_dal_oracle.php

### ISSUE THREAD

**Issue by haneefputtur** [tecnickcom/tcexam#168]
Hi i am trying TCEXAM with oracle. I am able to setup and it partially works fine now.
I am getting following error message now when I go to take tests.

ERROR: [2] oci_fetch_assoc() expects exactly 1 parameter, 2 given | LINE: 128 | FILE: D:\xampp\htdocs\exam\shared\code\tce_db_dal_oracle.php

ERROR: [2] array_change_key_case() expects parameter 1 to be array, null given | LINE: 130 | FILE: D:\xampp\htdocs\exam\shared\code\tce_db_dal_oracle.php

ERROR: [2] array_map(): Argument #2 should be an array | LINE: 131 | FILE: D:\xampp\htdocs\exam\shared\code\tce_db_dal_oracle.php

Is there anything  am missing ?
I am using oracle 11G.
# Connectivity no issue
# Creating test works fine.

Your help is highly appreciated. [Attached screenshot for reference]

![image](https://cloud.githubusercontent.com/assets/6358796/21717094/41ccc696-d428-11e6-9980-0423035ce98f.png)

**Comment by nicolaasuni** [comment]
Since the Windows system and Oracle database are proprietary, it is difficult to find free support.
If you can, my advice is to use a Linux environment instead with an open database like MySQL or PostgreSQL
