### ISSUE TITLE
Provide a docker image for TCExam

### ISSUE THREAD

**Issue by doomsbuster** [tecnickcom/tcexam#170]
Shipping TCExam in pre-fabricated docker containers will make it easy for users to install TCExam with simple commands without worrying about software versions, dependencies and other issues involved in configuration and setup of the TCExam application.

**Comment by doomsbuster** [comment]
I have a Docker image ready to ship and I am happy to contribute the docker file and image to the project.

**Comment by nicolaasuni** [comment]
A Docker container is not intended to be used for persistent storage, so the database should be installed somewhere else. As TCExam can be installed with a lot of different options, the only usage of such container will be just for a quick demo, as it shouldn't be used in any production environment.

**Comment by doomsbuster** [comment]
Dependencies on specific versions of PHP, MathJAX, other GDP libraries can be preconfigured. A database initialization and MySQL configuration is a part of the docker image. This simplifies the process of getting up and running fairly quickly. Shipping the TCExam instance from one machine to another also becomes a very trivial task with containers. e.g. imagine running TCExam on Ubuntu 16.04 LTS which comes with latest version of MySQL. Users using docker containers are insulated from such issues while the main code base is upgraded to support latest frameworks.

**Comment by shivamb** [comment]
@doomsbuster 
Possible for you to share the image?

**Comment by shivamb** [comment]
We may always customise the options with environment variables and arguments. We can configure the installation with scripts based on arguments passed.

**Comment by doomsbuster** [comment]
@shivamb sure. Let me find it on docker hub.

**Comment by AmanSaurav** [comment]
@doomsbuster have you uploaded on docker?

**Comment by KlavsKlavsen** [comment]
@nicolaasuni you seem to not know how kubernetes (which runs everything in docker) works? you simply volume in (ie.mount) the persistent storage you need for your database - and the settings are either given via env. variables - or mounted in too. This works beautifully and ensures everyone who uses that - actually run on the EXACT same setup (software wise) - and still can have their individual configs and datasets - making it a very homogenic environment - no matter which host it actually runs on below.

**Comment by KlavsKlavsen** [comment]
@doomsbuster It would be fantastic if you would make a PR for your Dockerfile atleast.. even if its not merged - the rest of us can use it. IMHO it SHOULD be merged, to start supporting a MUCH easier way for everyone to use this software and do updates in a much easier and safer way.
