### ISSUE TITLE
It is not possible to pass socket to mysqli_connect

### ISSUE THREAD

**Issue by brempusz** [tecnickcom/tcexam#171]
Noticed in ver. 13.3.0.

For legacy (MYSQLDEPRECATED) connection is created from host/port, so mysql socket path can be passed as `$port` variable:
`if (!$db = @mysql_connect($host.':'.$port, $username, $password)) {`

latest code is different:
`if (!$db = @mysqli_connect($host, $username, $password, $database, $port)) {`

It is not possible to pass socket path because it should be passed as last parameter (after `$port`) to `mysqli_connect`.

Workaround:
change tce_db_config.php: `define('K_DATABASE_PORT', NULL);` (it will not work with empty value: `''`)

set `mysqli.default_socket` to socket path (in php.ini / .htaccess / apache config file / etc.), 
for example, apache config entry for specific location:
```
<Location /tce/>
...
php_value mysqli.default_socket "/path/to/mysql.sock"
...
</Location>
```

Please update documentation to make more clear how to use custom socket path (or maybe implement add K_DATABASE_SOCKET option or detect if K_DATABASE_PORT is [0-9]+ - if not, use it as socket path?).

**Comment by nicolaasuni** [comment]
As suggested, I have added a note at:
https://github.com/tecnickcom/tcexam/blob/develop/shared/config.default/tce_db_config.php#L43

**Comment by brempusz** [comment]
Thanks!
