### ISSUE TITLE
removing "default group" is possible?

### ISSUE THREAD

**Issue by andre76padilha** [tecnickcom/tcexam#172]
I have recently installed TCExam and I have some simple doubts which I could not find any answer:
1. Is it possible to remove the default group without corrupting somehow the admin account? (this is because I want my students to login by choosing only the groups they'll belong to, but for registration, the default group appears to new accounts and they can choose it. That's what I'd like to remove from the login screen)
2. Is it possible to avoide self-registration? (it is because I'd rather insert all my students instead of they doing it by themselves)

**Comment by nicolaasuni** [comment]
1. You can edit shared/config/tce_user_registration.php and set the default group ID in the K_USRREG_GROUP constant for new registrations. In this way you can have a separate group for registration requests.

2. Yes, set K_USRREG_ENABLED to false in shared/config/tce_user_registration.php

Note that you can let your users registering themselves and then approve the registrations by raising their level.
Please upgrade to version 14.
