### ISSUE TITLE
PHP Fatal error:  Call to undefined function password_hash() 

### ISSUE THREAD

**Issue by rhiann0n** [tecnickcom/tcexam#173]
I am running tcexam on cents 6.7, and I did run into a few issues that I had to fix as I go along, and I'm happy to help write up some scripts or documentation on fixes, or help with auth improvement. 

Thus far, requires PHP 5.5 for RHE distros due to the password function in the following error:

` [error] [client x.x.x.x ] PHP Fatal error:  Call to undefined function password_hash() in /var/www/html/shared/code/tce_functions_session.php on line 234`

To describe what happened, I entered database credentials, and was met with a blank screen, no progression further to the actual application.  Determined this was due to PHP version issue and the password function used on line 234 of tce_functions_session.php

**Comment by nicolaasuni** [comment]
The new TCExam version 14 requires PHP 5 >= 5.5.0 or PHP 7
If you are using an older version of PHP, I highly recommend to update.
