### ISSUE TITLE
Questions only displayed 1 time

### ISSUE THREAD

**Issue by vivinrokt** [tecnickcom/tcexam#174]
Hello everybody....
I want to display the question only 1 time on the test. And after selecting the next question, the previous question can not be displayed again. how to configure it??
![example](https://cloud.githubusercontent.com/assets/28525701/25794012/5153d074-33f9-11e7-9cf9-cf7eab2c9940.png)

**Comment by nicolaasuni** [comment]
On the "question" page you can select the "fullscreen" option to remove any control.
You also have the "automatic next" option for the MCSA questions, so the page moves to the next question as soon as an answer is selected.
On the "test" page you can also disable the "questions menu".
