### ISSUE TITLE
Undefined function for password hash

### ISSUE THREAD

**Issue by ebenezery4** [tecnickcom/tcexam#176]
I downloaded the latest commit and after all the installation process i encounter this error:

Fatal error: Call to undefined function password_hash() in C:\xampp\htdocs\exam\shared\code\tce_functions_session.php on line 234

is it a bug or php version

**Comment by nicolaasuni** [comment]
You are probably using an unsupported version of PHP.
TCExam requires at least PHP 5.4.
Please upgrade to a newer PHP version.
