### ISSUE TITLE
TCExam & PHP7

### ISSUE THREAD

**Issue by drexvictor** [tecnickcom/tcexam#178]
I have installed (using the install.php) TCExam on apache2, php7 and mysql5.7.

After login and authenticaation, I am still presented with the login screen and nothing else. How do I get this resolved.

![screenshot from 2017-06-10 11-39-32](https://user-images.githubusercontent.com/9039228/27000504-804f6752-4dd1-11e7-897b-96b3ebbd59f2.png)

**Comment by saumyakswain** [comment]
Install php-5.6, enable it and disable php-7. That is one of the solutions.

**Comment by nicolaasuni** [comment]
Have you tried with a different browser? are you blocking cookies?

**Comment by saumyakswain** [comment]
Enable php errors, E_ALL. You can see the error.

**Comment by aamirbekov** [comment]
With Google Chrome I have the same problem, does not work login. With Firefox and Internet Explorer login works.

**Comment by nicolaasuni** [comment]
Try to set K_CHECK_SESSION_FINGERPRINT to false in the shared/config/tce_config.php file.
