### ISSUE TITLE
Issue when sending emails to users from Tests->Users->Test results

### ISSUE THREAD

**Issue by levelit** [tecnickcom/tcexam#179]
Hi there,
I hope you can help me out with this issue we've found.

When you land in the page "http://localhost/tcexam/admin/code/tce_show_result_user.php" to select a test and a particular user to check the results and send an email with them, TCEXAM sends **all results to all users** if you did not change anything selected by default as "test" and "user test" right after you landed in the page.

When you click the "send email" the resulting URL looks like this: "http://localhost/tcexam/admin/code/tce_email_results.php?mode=1&menu_mode=startlongprocess"

If...after that I select a different test or user, it sends the emails but...to **all users in that particular test**. It looks like it is not applying the filter of the selected user. The resulting URL looks like this:
"http://localhost/tcexam/admin/code/tce_email_results.php?mode=1&menu_mode=startlongprocess&test_id=5&testuser_id=96"

We believe these behaviours look weird and it may create a problem if all results are sent to all users even for locked exams.

Could you give me a hand on this?

Thanks
Vero

**Comment by levelit** [comment]
Sorry, I forgot to add that the same happens with buttons "PDF" and "send email + PDF".

Many thanks in advance!

**Comment by nicolaasuni** [comment]
Are you using the latest TCExam version available here?

**Comment by levelit** [comment]
Hi there! Yes, I downloaded the lates version from here.

**Comment by nicolaasuni** [comment]
I am unable to reproduce the issue using TCExam 14.0.2.
Please be sure that ou press the "select" button after selecting the user and before clicking on "send emails".

**Comment by nicolaasuni** [comment]
Closing this because lack of activity.
