### ISSUE TITLE
Error while generating a PDF offline

### ISSUE THREAD

**Issue by A-Gandotra** [tecnickcom/tcexam#183]
i am getting the following error while after i try to create a PDF offline

**ERROR: [2] getimagesize(/tcexam/cache/error1.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/error1.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/include/tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/1.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/1.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/include/tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/err.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/err.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/include/tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/err.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/err.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: /opt/lampp/htdocs/tcexam/shared/tcpdf/include/tcpdf_static.php
TCPDF ERROR: Some data has already been output, can't send PDF file**

Looks like it has something to do with the screenshots that i used in the questions. 
Can anyone help please?

**Comment by A-Gandotra** [comment]
Hi @nicolaasuni !! Can you help with this issue please ?

**Comment by nicolaasuni** [comment]
Please check if the cache folder has writing permission for the web user.

**Comment by shakermohamed** [comment]
i don't know how to do that. please tell me how

**Comment by ninhthithanhtam** [comment]
My tests display the Vietnamese language on TCExam correctly. But when I export the PDF file, it replaces Vietnamese characters by '?'. Can you help me fix this?

**Comment by tonis-ls** [comment]
Same error while printing a test result:

ERROR: [2] imagecreatefrompng(/tcexam/cache/ora_57.png): failed to open stream: No such file or directory | LINE: 7033 | FILE: /srv/www/tcexam/shared/tcpdf/tcpdf.php
TCPDF ERROR: Some data has already been output, can't send PDF file

TCExam directory has owner permission for webserver user:
sudo chown -R apache:apache /srv/www/tcexam/

TCExam ver. 14.0.2

**Comment by shakermohamed** [comment]
heeeeeeeeeeeeeeelp nicolaasuni

**Comment by grog57** [comment]
Same error to me:
ERRORE: [2] imagecreatefrompng(/tcexam/cache/fratta4.png): failed to open stream: No such file or directory | LINE: 7033 | FILE: /home/anughea/www/tcexam/shared/tcpdf/tcpdf.php
ERRORE: [2] Cannot modify header information - headers already sent by (output started at /home/anughea/www/tcexam/shared/code/tce_functions_errmsg.php:77) | LINE: 7645 | FILE: /home/anughea/www/tcexam/shared/tcpdf/tcpdf.php
TCPDF ERROR: Some data has already been output to browser, can't send PDF file

I've tryed a lot of solution without succes (gif and png without transparency, using only jpg, permission on cache) - 
Any other idea? could be the  ALLOW_URL_INCLUDE off?
Thank you

**Comment by nicolaasuni** [comment]
Try to temporarily change the folder permission to be sure it is not a permission problem:

sudo chmod -R 777 /srv/www/tcexam/cache

**Comment by grog57** [comment]
Thank you Nicola. Already done, unfortunately itsn't the permission, neither allow_url_include Off, could be a remote server configuration as with xampp works well and in the past on other remote server all was ok.
Waiting for other ideas.

**Comment by virugge** [comment]
I also have the same error when trying to generate a pdf test.
Please, help me.

```
ERRORE: [2] getimagesize(/var/www/vhosts/miodominio.eu/tcexam.miodominio.eu/2017/cache/__tcpdf_5866221ca763916935e4c9e75c8e7331_imgmask_alpha_f20ae0141e8397811cfa9f4989350a66): failed to open stream: No such file or directory | LINE: 6855 | FILE: /var/www/vhosts/miodominio.eu/tcexam.miodominio.eu/2017/shared/tcpdf/tcpdf.php
ERRORE: [2] getimagesize(/var/www/vhosts/miodominio.eu/tcexam.miodominio.eu/2017/cache/__tcpdf_5866221ca763916935e4c9e75c8e7331_imgmask_plain_f20ae0141e8397811cfa9f4989350a66): failed to open stream: No such file or directory | LINE: 6855 | FILE: /var/www/vhosts/miodominio.eu/tcexam.miodominio.eu/2017/shared/tcpdf/tcpdf.php
TCPDF ERROR: Some data has already been output, can't send PDF file

```

**Comment by pintraj** [comment]
I want to contribute the code. I have made some css changes. can i know how to contribute

**Comment by pantsmanuk** [comment]
Everyone suffering the "failed to open stream" error - from my local testing in v14.0.3, tcpdf.php isn't generating the path to the image files directly. Instead of making a fully qualified filesystem path ("/full/path/to/cache/filename.png") or a relative filesystem path ("../../cache/filename.png"), it just tries to work with "/cache/filename.png". Unfortunately, the functions being called around at LINE 6850 are all filesystem-aware and need either full paths or (working) relative paths. For our installation, a quick enough workaround was to add the following at LINE 6842 in shared/tcpdf/tcpdf.php:-

`                       // HORIBLE KLUDGE - make $file an FS relative path
                        if ($file[0] === '/') {
                                $file = "../.." . $file;
                        }`

@nicolaasuni I don't have time to make a proper fix and pull request right now, but I'm guessing that whatever populates $file and calls Image() isn't making use of the K_PATH_CACHE constant. Hope this helps you find the cause and correct it.

**Comment by nicolaasuni** [comment]
To me this seems a misconfiguration issue.
Please check the shared/tce_path.php file.

**Comment by pantsmanuk** [comment]
Actually @nicolaasuni  - I'm not too busy this afternoon, so I dropped a 'print_debug_backtrace()' in place of my horrible kludge and I think the "problem" lies inside openHTMLTagHandler().

Up until this function gets hold of the image, the image is (quite rightly) an "HTML Image" - the path is quite correct for that purpose. 

I'm writing this immediately after my first run (having added the debug backtrace), so the following is all speculation on my part - openHTMLTagHandler appears to be passing the URL path to Image as if it's a file-system path.

**Comment by nicolaasuni** [comment]
Since this bug was opened several versions have been released and I am unable to reproduce the issue.
