### ISSUE TITLE
Test Buttons

### ISSUE THREAD

**Issue by rwahdan** [tecnickcom/tcexam#187]
Hi,
I have the site up and running but a have a big problem, when test starts i don't see the buttons (prev, confirm and next) and I have no clue why! I know it is in the file "tce_test_execute.php" but I am not sure why they are not shown in the exam!

Thanks,
![no_buttons](https://user-images.githubusercontent.com/29956998/29966091-630a46f8-8f21-11e7-8ced-336384ca3088.jpg)

**Comment by nicolaasuni** [comment]
On the questions editor, check if you have enabled the "automatic next" option, it should be unselected.
Check also the "questions menu" option in the test editor, it should be selected.
If this doesn't work, please check the web page source code (the HTML code) to see if the buttons are there.

**Comment by nicolaasuni** [comment]
Closing this because lack of activity.

**Comment by ajeducation** [comment]
I have installed the TCExam 14.0.3 and having same problem that Test Navigation button are hidden in webpage source code.
1. Automatic Next in question editor is disabled.
2. Question Menu in test editor is enabled.

**Comment by ajeducation** [comment]
Enabled the navlink for next and previous button in tcexam/shared/code/tce_functions_test.php

**Comment by psnayak2007** [comment]
How to change the button value to Sentence case?
