### ISSUE TITLE
Please add MP4 and MOV media types to config

### ISSUE THREAD

**Issue by waginfo** [tecnickcom/tcexam#189]
With each re-installation, I constantly have to edit the config.php script under admin/config for enable uploading of MP4 and QuickTime MOV files which are very common file formats, especially on mobile devices.
Could you please add these to the default allowed upload extensions?
i.e.:

define('K_ALLOWED_UPLOAD_EXTENSIONS', serialize(array('csv', 'tsv', 'xml', 'txt', 'png', 'gif', 'jpg', 'jpeg', 'svg', 'mp3', 'mid', 'oga', 'ogg', 'wav', 'wma', 'avi', 'flv', 'm2v', 'mpeg', 'mpeg4', 'mpg', 'mpg2', 'mpv', 'ogm', 'ogv', 'vid', 'pfx', 'pem', 'crt', 'mp4', 'mov')));

Thanks

**Comment by nicolaasuni** [comment]
TCExam do not overwrites the existing configuration files, so you should be able to keep the old ones, unless it is a major change. Alternatively you should have your orchestration scripts to fill the config files as required for your system.
