### ISSUE TITLE
[ASK] Making Question that has more than one answer by having a weighting value for each answer

### ISSUE THREAD

**Issue by Dedyverdian** [tecnickcom/tcexam#190]
Hi, I want to ask about the features in TCExam ,,,
How to create a question that has more than one answer by having a weighting value for each answer.
example:
1. What are your goals?
answer
a. Doctor (get 5 points)
b. Master (get 4 points)
c. Army (get 3 point)

all the user's answer is correct, it's just that, each answer has its own value.

Sorry for my bad english
Thank you

**Comment by nicolaasuni** [comment]
This is something not supported.
The supported question types are described at: https://tcexam.org/docs/question_types/

**Comment by edahkaben** [comment]
We hope this feature available in TCExam next release
