### ISSUE TITLE
Anonymous users online

### ISSUE THREAD

**Issue by tcexamuser** [tecnickcom/tcexam#192]
User that logged in and logged out are still online and can't log in anymore... They are appearing to be online but not
user | level | IP
-- | -- | --
(- [0212f8a3]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
Mangrubang, Angel Ruth  (zheacastro) | 1 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [5c815427]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [f2e0f9a1]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:013c
(- [e7bced4a]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [e91be820]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [e6e30c98]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [082db3c3]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [1362abad]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [6ab0a844]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [e808b79d]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [22a26414]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [3289d5de]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [ceebef2b]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
paddayuman, geyan (IMSUPERGEYAN) | 1 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [51556cfd]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [b8fb4a2e]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:013c
(- [e3a5c993]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [ab90a504]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [a922841c]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [795c2030]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [3877a937]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
Miranda, Jenifer (jenifermiranda) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [e50af882]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [a2a9d4df]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [91ede410]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [3e631bf1]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [0596391e]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [54246e7a]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
Miranda, Jenifer (jenifermiranda) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [c192aed8]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [03aaed3c]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [7738d5c7]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:013c
(- [cbba527e]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [0f268385]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [0546cef8]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
Mangrubang, Angel Ruth  (zheacastro) | 1 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [70f6fe9f]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:013c
(- [0803e721]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [9f48257a]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [5c3b3104]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [0768ccb8]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [62f9c328]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [2a6b5d65]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:013c
(- [9f4db334]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:010a
(- [27b3c55b]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:010a
(- [67f4039d]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [aeea4a85]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
(- [40a4476f]) | 0 | 0000:0000:0000:0000:0000:ffff:c0a8:0101
paddayuman, geyan (IMSUPERGEYAN) | 1 | 0000:0000:0000:0000:0000:ffff:c0a8:0101

The above are the ANONYMOUS users that populate the ONLINE USER LIST. Which it think is the reason why user cannot log in once they logged out.

![image](https://user-images.githubusercontent.com/31914469/30525826-00a0f6e2-9c41-11e7-804c-22573ddfd8ec.png)

**Comment by nicolaasuni** [comment]
I am not sure to understand the problem, can you explain it with an example?

**Comment by tcexamuser** [comment]
Hi
Thanks for responding..When users log in, you can check whose online on the admin account through the User Tab - ONLINE LIST, there are anonymous users ( No User Credendials) who are online, which I think using the memory of the server. And also when Users Log Out, they are not logged out in the ONLINE LIST..This makes user unable to log in back because the server thinks they are still logged in..
Thanks



Sent from Yahoo Mail for iPhone

On Sunday, September 17, 2017, 7:50 PM, Nicola Asuni <notifications@github.com> wrote:


I am not sure to understand the problem, can you explain it with an example?

**Comment by tcexamuser** [comment]
![image](https://user-images.githubusercontent.com/31914469/30525823-e5fa9cbc-9c40-11e7-8fd5-d131e9647434.png)

**Comment by tcexamuser** [comment]
Where does these anonymous users coming from?..They are populating the online list of users making registered users unable to connect..

**Comment by nicolaasuni** [comment]
An anonymous user entry is created every time a user connect to TCExam without being authenticated.
These virtual session are automatically removed after expiration time.
There is nothing unusual.
