### ISSUE TITLE
cannot set virtual host

### ISSUE THREAD

**Issue by tcexamuser** [tecnickcom/tcexam#193]
I have set a virtual host on my server, but when i type in the virtualhost name on a client PC, the browser cannot locate the said site...I have to manually type the IP/tcexam address of the server in order for the browser to access the tcexam site.

![image](https://user-images.githubusercontent.com/31914469/30526845-3c086f90-9c54-11e7-882a-2590b65f5703.png)

![image](https://user-images.githubusercontent.com/31914469/30526848-446d3b3e-9c54-11e7-990b-2be480c48ada.png)

![image](https://user-images.githubusercontent.com/31914469/30526850-4e8581bc-9c54-11e7-95ab-eae90cd932fe.png)

![image](https://user-images.githubusercontent.com/31914469/30526852-55bda270-9c54-11e7-9ff3-235d0366a3a9.png)

**Comment by nicolaasuni** [comment]
This is not a TCExam specific question.
Please search online how to set a generic virtual host, there a plenty of guides and examples.
I suggest to use Apache or nginx as a web server.
