### ISSUE TITLE
i can’t login, and no email

### ISSUE THREAD

**Issue by mandrivagnome** [tecnickcom/tcexam#195]
i installed tcexam, but i can’t login.
my websit: ekhtibar.com

i tried to add new user with new email but tcexam can’t login, and not send any email to me (amin) or the user ?

**Comment by nicolaasuni** [comment]
If you are upgrading from a previous version, the password hashing code has changed, so you
have to reset all passwords.

To reset the admin and anonymous passwords you can execute the following
code in your database:

```
UPDATE tce_users SET
user_password='$2y$10$f4hALLkUK06EgTQ8b1OWTu4JFvRTXRc0cxqSz5sKaLKhCNGeLemTO'
where user_name='admin';
```

Alternatively you can register a new user and then manually change the
user level in the tce_user database to 10.
