### ISSUE TITLE
Update: You are trying to log too many times and .......before the next attemp: 4096

### ISSUE THREAD

**Issue by ilias-ec** [tecnickcom/tcexam#197]
I use tcexam to many years...
Today (19/10/2017) 11 students in login page gives the username and password for first time.
4 students make successful login.
the 7 students type the login and password and then on screen immediately appears:
"You are trying to long to many times and too fast. Please wait the following number of seconds before the next attempt: 4096."
The 7 students does not make the test because 4096 sec (1 hour and few minutes) is to many time to wait... and make the test at the next week....
How to remove or change the waiting time?
The students using the tcexam only:
-  in Computer Lab 
- at specific date/time and when I am present
- no Internet connection at test time.
Update: Today (20/10/2017) the same problem.... other students..
I find something ...all students use TCExam 14.0.2, Firefox 56.0 under Ubuntu mate 16.04.03 LTS the same under Win7.
I change browser to Chromium and i make some tests and i think it is ok...
Update 25/10/2017: The same problem with Chromium when the students, once time, type the login/password and then  authenticate and the above message ("You are trying to long ....the next attempt: 4096.") appears....I find a temporary solution: When the message appears I change the browser and the student make the test. To be more specific: If the student use Chromium and the message appears, close the Chromium and open Firefox and works...and the opposite. It is not practical but it works.

**Comment by nicolaasuni** [comment]
This is a feature to avoid brute forcing the access to TCExam.
To disabel it or change the ratio you can edit the K_BRUTE_FORCE_DELAY_RATIO constant in shared/config.default/tce_config.php
Set it to 0 to disable the delays.
