### ISSUE TITLE
send a msg for all users

### ISSUE THREAD

**Issue by mandrivagnome** [tecnickcom/tcexam#199]
Dear Tcexam team
i hope you can add this features:
1- add dropdown to select if the user ( teacher or student), and add option for admin, to get the teacher (level 5) automaticly, this dropdown in users page, selected when they “sign in”.
2- add msg window to send a msg for all users, or teachers (level 5) only, or students (level 1) only.
msg for new school year, for exam seson, or for anything.

best regards

**Comment by nicolaasuni** [comment]
Thanks for your sugegstions.
1. Due to the nature of the application, each level should be manually assigned by an administrator.
2. TCExam only manages messages related to exams and tests. For anything else it is better to use another tool.
