### ISSUE TITLE
level 5 

### ISSUE THREAD

**Issue by mandrivagnome** [tecnickcom/tcexam#201]
I created a module using admin, so all 5 level moderators can see and edit topics and questions. I created a new account and called it Beta, and I gave it a Level 5 license, but I do not know how to transfer ownership of this module from admin to beta, to let the level 5 supervisors can not see and edit topics and questions.

**Comment by nicolaasuni** [comment]
To change the level of a php page please set the $pagelevel variable at the top of the file:
$pagelevel = 5;
