### ISSUE TITLE
question importer (failed)

### ISSUE THREAD

**Issue by delromano** [tecnickcom/tcexam#206]
I imported tests using the TSV format but although the message at end upload csv file was all right I noticed that actually the queries were not loaded. I also noticed that going to "file manager" the file I had uploaded did not have permissions all open. Execution permits are missing. In fact a few months ago it all worked regularly and in the meantime there was a system update of our school server.

**Comment by delromano** [comment]
![image](https://user-images.githubusercontent.com/28058731/32578550-f026e95a-c4dd-11e7-8a9c-c9a947013015.png)
 
i have upload screenshot where appear the permissions of uploaded file

**Comment by nicolaasuni** [comment]
Please be sure that you are using the latest TCExam version and that the import format is correct.
For an example of the correct format, go to the Questions List page:
admin/code/tce_show_all_questions.php
and export an existing list in XML or TSV.
