### ISSUE TITLE
Random Question and order by TOpics

### ISSUE THREAD

**Issue by lpselebong** [tecnickcom/tcexam#211]
Hi, how to make random qustions and order only by Topics. I've made 3 Topics with same type (Single Answer), different Difficulty, Example : 
Modul I : 
Topic I : 50 questions, 2 Difficult, 2 choice (True/False) ======> These will be pulled only 25 questions
Topic II : 65 questions, 3 Difficult, 4 choice (True/False/False/False) ======> These will be pulled only 55 questions 
Topic III : 15 questions, 4 Difficult, 4 choice (True/False/False/False) ======> These will be pulled only 10 questions 

I want to make test with this figure : 
Questions 1 to 25 from Topic I, randomized from 50 qustions
Questions 26 to 80 from Topic II, randomized from 65 qustions
Questions 81 to 90 from Topic III, randomized from 15 qustions

Please help me, I've been tried for 3 days and I still cannot resolve this.
Thanks

**Comment by nicolaasuni** [comment]
You can select different number of questions from each topic but if you choose the random selection, then also the topics will be randomized.
If you need a test to have 3 separate sections you can always split it in 3 different tests.
