### ISSUE TITLE
ATTENTION: [4096] ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() | LINE: 37 | FILE: C:\xampp\htdocs\shared\code\tce_functions_session.php

### ISSUE THREAD

**Issue by altanop** [tecnickcom/tcexam#217]
hi at http://localhost/public/code/index.php 
tcexam show this message 

ATTENTION: [4096] ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() | LINE: 37 | FILE: C:\xampp\htdocs\shared\code\tce_functions_session.php

does anyone have the same problem?

**Comment by nicolaasuni** [comment]
This depends on the php settings on your server.
You should ask your server administrator.

**Comment by IdenticalParticle** [comment]
Remove    ini_set('session.save_handler', 'user');                       /shared/code/tce_functions_session.php

**Comment by damms005** [comment]
@IdenticalParticle at the cost of not having tcexam manage the cleaning-up of your db for you! (check the session functions in `shared/code/tce_functions_session.php` for more details of what you will be missing)
