### ISSUE TITLE
Session error at the bottom of all pages

### ISSUE THREAD

**Issue by IdenticalParticle** [tecnickcom/tcexam#219]
Hi, I am getting the error at the bottom of all pages:

ERROR: [2] Unknown: Session callback expects true/false return value | LINE: 0 | FILE: Unknown
ERROR: [2] Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) | LINE: 0 | FILE: Unknown

Fresh environment of Debian9.4+PHP7.0+Postgres9.6

**Comment by nicolaasuni** [comment]
This seems a problem with your php settings.
Please ask your server administrator if you don't have the permission to change settings.

**Comment by IdenticalParticle** [comment]
I install everything myself. PHP settings file is default.
The test found the problem caused by Postgres. With Mysql, everything is normal (Remove    ini_set('session.save_handler', 'user'); ).
