### ISSUE TITLE
Error while generating a PDF

### ISSUE THREAD

**Issue by wensiso** [tecnickcom/tcexam#222]
I am getting the following error while after i try to create a PDF:

ATTENTION: [8192] The each() function is deprecated. This message will be suppressed on further calls | LINE: 572 | FILE: /var/www/html/tcexam-copy/admin/code/tce_pdf_testgen.php
TCPDF ERROR: Some data has already been output, can't send PDF file

URL: http://localhost/tcexam/admin/code/tce_pdf_testgen.php?test_id=1&num=1

Can anyone help please? The exam has only text, without images.

**Comment by nicolaasuni** [comment]
The each function has been deprecated starting from php 7.2.
I have update TCExam to replace while/each with foreach.
