### ISSUE TITLE
Fatal error on PDF creation of single user results (test->Users-PDF)

### ISSUE THREAD

**Issue by ITMATD** [tecnickcom/tcexam#224]
I am using the TCExam version 12.2.5 it was working fine but now I am not able to create the pdf of individual student results. i also tried it on version 13 but i get the same problem.
Error : Fatal Error : Maximum Execution Time of 30 seconds exceeded in C:\wamp\www\TCE\shared\tcpdf\tcpdf.php on line 4087

![image](https://user-images.githubusercontent.com/40887906/42373662-11c440e0-812f-11e8-860e-e728291b5733.png)

**Comment by nicolaasuni** [comment]
Please upgrade to the latest TCExam version and then increase the maximum execution time in the php settings.
