### ISSUE TITLE
Question Explanation is not displayed

### ISSUE THREAD

**Issue by afridiwaqar** [tecnickcom/tcexam#228]
Hello

I conducted a test using TCExam and several of the questions had explanation but none was displayed. I googled around, saw this link https://github.com/tecnickcom/tcexam/issues/145 but the report to the user also didn't work and there is no option for displaying explanation. 

Kindly help

Regards

**Comment by nicolaasuni** [comment]
The question explanation displayed in
admin/code/tce_edit_question.php
when clicking on the explanation "show" button.

Question explanations are also shown in the test to the administrators, and also to the users results if the option "reports to users" is enabled.

**Comment by afridiwaqar** [comment]
I dont know why was this issue closed without properly addressing it.

about the answer, I already know how to add explanation, I also know about enabling the "report to users" which I mentioned in my question as well, but still the explanation is NOT displayed to users regardless of all these stuff being enabled or added and this is where I was seeking your help.

**Comment by afridiwaqar** [comment]
Thanx for reOpening the issue, Well bad luck as I still cant see the explanation, I downloaded the recent version, also refreshed the database, you know just in case and added question with explanation but when I execute the test, I can only see questions, not there explanation (yes I have check the Report to users checkbox.)

Still No luck :(
