### ISSUE TITLE
 there are no available tests

### ISSUE THREAD

**Issue by nashot99** [tecnickcom/tcexam#229]
I created a sample test using the TCExam guide to First Exam. However I kneep getting this message:
 there are no available tests!

**Comment by japjeebrijesh** [comment]
Changing the time zone in php.ini file should solve the problem

**Comment by mazydah** [comment]
Hello I am having the same issue, the

**Comment by jsaiko** [comment]
Just wanted to pop in with a solution I wasn't able to find anywhere else on the web.  There is a spot for authorized IPs that doesn't seem to play well with IPv6.  I disabled IPv6 on my server and restarted my browser forcing IPv4.  Once I did this the tests started showing up.
