### ISSUE TITLE
Images in questions are not appearing.

### ISSUE THREAD

**Issue by amirafzal** [tecnickcom/tcexam#231]
Hi I have installed the latest version 14.1.8, Now when I upload and embed the  image in question, it does not appear. 

Instead I can see only image icon (place holder)

![error](https://user-images.githubusercontent.com/11245072/46632850-9e665c80-cb54-11e8-82cf-73ef965c1fb1.png)

Appreciate if someone can help.

**Comment by nicolaasuni** [comment]
Please check if the webserver user (i.e. www-data for Apache) has the permission to write the cache folder.
Then try to upload an image file using the Media File Manager interface ans see if it works.

**Comment by nicolaasuni** [comment]
Close for lack of activity.
