### ISSUE TITLE
Issue in installing TCExam on Windows Server 2008 R2 

### ISSUE THREAD

**Issue by sagar002100** [tecnickcom/tcexam#235]
Hello, 
      I am trying to install TCExam on Windows Server 2008 R2. I installed XAMPP-win32-7.2.9.0-vc15-installer.exe on it and all services are running successfully. 
After that I placed "Tcexam" setup folder in C:\xampp\htdocs\ . 
But when I tried to install http://my-IP/tcexam_folder/install/install.php. In this windows I set my database password. After that i got an error " create or replace database and get connection".... [ERROR]. Check 
![capture-01](https://user-images.githubusercontent.com/44391588/47341474-b2ff3480-d6be-11e8-9bc8-25d075395abe.PNG) . 

After that when i clicked on "Click here to start TCexam " .. Check attached file 
![capture-02](https://user-images.githubusercontent.com/44391588/47341562-f22d8580-d6be-11e8-80fe-7be782a31852.PNG) for that.. 

Please help me in that..

Sagar Patel

**Comment by nicolaasuni** [comment]
You can manually install the database by following the manual procedure at:
https://tcexam.org/docs/installation/
