### ISSUE TITLE
TCExam 13.3.0 and PHP 7

### ISSUE THREAD

**Issue by levelit** [tecnickcom/tcexam#238]
Hello there!

One quick question. We have version 13.3.0 installed and due to other apps we may need to migrate from PHP 5.6 to PHP 7.

Could you please help us knowing if TCExam v 13.3.0 runs without problems under PHP 7?

Many thanks,
Regards,
Vero

**Comment by damms005** [comment]
If you do not mind, I will advice that you switch to the latest version (currently 14.1.9). TCExam fully supports PHP 7

**Comment by nicolaasuni** [comment]
Upgrade to the latest version solves the problem.
