### ISSUE TITLE
Error - Test Management

### ISSUE THREAD

**Issue by PhanindraGIS1in** [tecnickcom/tcexam#239]
Hi Team,

I have installed Tcexame in Windows server 2012 R2 (IIS) and I tried followed 'first_test' instructions but I am getting the following exception. 

![image](https://user-images.githubusercontent.com/29281429/50969704-48afa080-1505-11e9-84d3-18633956a325.png)

Thank you in advance.

**Comment by nicolaasuni** [comment]
Seems like you are missing some configuration data for mysql.
