### ISSUE TITLE
VERY URGENT - I lost all the databses after a tcexam test... 

### ISSUE THREAD

**Issue by ilias-ec** [tecnickcom/tcexam#240]
At Friday 11/1/2019 - 08:30 
I make a tcexam test in 13 students. All students finish correctly because i see on screen the test results.
The students finish around 09:00.
Each of students make disconnect from tcexam and close the browser.
The same, I made, on tcexam server (Ubuntu 14.04 - tcexam version i do not remeber - not the latest) disconnect from tcexam - close firefox - lock screen and leave from Computer Lab. No body else uses the Computer Lab.
I came back to  Computer Lab at around 15:00 to make a tcexam backup.
Open firefox - open tcexam and on screen
![default](https://user-images.githubusercontent.com/5635375/51072905-b7117180-1671-11e9-9834-389fb430a8bf.png)
What!!!!!!!!   The first heart attack coming....
after few deep breaths starting to think....open phpmyadmin and .....
![default](https://user-images.githubusercontent.com/5635375/51072935-2f783280-1672-11e9-87a0-c2e50bf36dcb.png)
second heart attack
I make reboot the server
The same .... unable to connect and no databases in phpmyadmin....
shoutdown the server and I leave from Computer Lab...
Today (Sat 12/1/2019) I write the problem....after to calm a little bit.....it is the first time....I use the tcexam arround 4 years... 
Please....where is the tcexam database.... I need the tests...
NO delete databases, no body uses after me the Computer Lab.....
Please help me asap.......

Also today after a short google search maybe the next print screen is helpfully
![default](https://user-images.githubusercontent.com/5635375/51073072-7a934500-1674-11e9-8dec-0af8de3506f4.png)

**Comment by nicolaasuni** [comment]
TCExam does not delete a database, unless you run again the installation scripts that should be deleted from your system after the first installation (as per instructions at https://tcexam.org/docs/installation/).
Please review the security of your installation.
