### ISSUE TITLE
Support for user passports

### ISSUE THREAD

**Issue by damms005** [tecnickcom/tcexam#241]
One of the important need case use for CBT is to be able to identify users taking the test. Consequently, it is important to have support for passports of users.

This mean both the database, user result pages, user data import; as well as other relevant TCExam features should be able to handle this.

Do yo have plans for this feature or I should quickly submit a PR for this?

**Comment by nicolaasuni** [comment]
Currently the "registration number" and "social security number" fields can be used to store the passport number, unless you need to use all of them?
