### ISSUE TITLE
ERROR: unable to load module `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//modules-Q16/coders/png.la': file not found @ error/module.c/OpenModule/1302

### ISSUE THREAD

**Issue by damms005** [tecnickcom/tcexam#244]
When importing @`code/tce_import_omr_answers.php`, the function `F_decodeOMRTestDataQRCode` generates a code like `/usr/bin/zbarimg --raw -Sdisable -Sqrcode.enable -q '/temp/phpIZqcJO'`. The command was not successful (I appended 2>&1 to debug that). The error is: 

> ERROR: unable to load module `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//modules-Q16/coders/png.la': file not found @ error/module.c/OpenModule/1302

However, the same code `/usr/bin/zbarimg --raw -Sdisable -Sqrcode.enable -q '/temp/phpIZqcJO'` when run from command line run successfully and outputs the decoded information. It also runs successfully when run with `php -r ...` from the command line.

What are your thoughts in resolving this? (btw, the file `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//modules-Q16/coders/png.la` is available. I even `chown` and `chmod`, all to no avail)

**Comment by nicolaasuni** [comment]
This seems more a system issue? Maybe some library version mismatch?

**Comment by nicolaasuni** [comment]
Closing for lack of feedback.
