### ISSUE TITLE
[8] Undefined variable: tmx | LINE: 119 | FILE: C:\Program Files\xampp\htdocs\tcexam\shared\code\tce_tmx.php

### ISSUE THREAD

**Issue by srikanth15794** [tecnickcom/tcexam#245]
I just configured the database and file paths and finally got the error:
8] Undefined variable: tmx | LINE: 119 | FILE: C:\Program Files\xampp\htdocs\tcexam\shared\code\tce_tmx.php
Can anyone tell me if I am missing something please ?

**Comment by damms005** [comment]
You may use PHP's silencer `@` for the offending variable

**Comment by mazydah** [comment]
Hello damilola and thank you for the timely response. I will do so and
revert

Thanks
