### ISSUE TITLE
TCExam Latex Configuration

### ISSUE THREAD

**Issue by nashot99** [tecnickcom/tcexam#248]
Hello,

I'm new to TCExam and am facing issue with LATEX configuration. I get [LaTeX: ERROR ] in the preview, when I add text using [TeX] button to a question.

As suggested in the LATEX_README.txt, I tried editing tce_latex.php but had no luck getting it to work so far. Upon looking thru' all the definitions in tce_latex.php, I don't see an entry to define K_LATEX_PATH_LATEX in the latest version that I downloaded from GitHub. Wonder is it expected to work without that? Or am I missing something? I searched all of the tcexam package directory structure and don't see a place to define it anywhere else either.

Can someone shed more light on this please?

**Comment by nashot99** [comment]
Well, I added the variable K_LATEX_PATH_LATEX with its value for my system, still no luck. Keep getting [LaTeX: ERROR ]

**Comment by nicolaasuni** [comment]
Have you tried to copy and edit the default LaTeX config file in TCExam?

**Comment by nashot99** [comment]
Yes, that's the first thing I tried, with the same result in the preview: 
[LaTeX: ERROR ]

**Comment by Psarmmiey** [comment]
Hello, I keep getting this error when I run the software 

"Warning: require_once(../config/tce_config.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/tcexam/public/code/index.php on line 34

Fatal error: require_once(): Failed opening required '../config/tce_config.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/tcexam/public/code/index.php on line 34"

Please I need anyone that has a clone of this software that works immediately at first run

**Comment by nicolaasuni** [comment]
Please try the debug options explained in the shared/config.default/tce_latex.php file.
