### ISSUE TITLE
disallow multi login

### ISSUE THREAD

**Issue by mamans86** [tecnickcom/tcexam#249]
I use tcexam for last 3 year, and working fine. 
The problem is, my student can login in two or more computer with their account at the same time. Is there any way to solve the problem without IP Address restriction. Is there any session restriction in TCExam? Thanks in advance.

**Comment by nicolaasuni** [comment]
If you are using the latest TCEXAM version, you should be able to set the "K_CHECK_SESSION_FINGERPRINT" constant to "true" to avoid this issue.
