### ISSUE TITLE
Security issue?

### ISSUE THREAD

**Issue by Pino50** [tecnickcom/tcexam#251]
During administrative login I get:
 
ATTENZIONE: [8] getmypid() has been disabled for security reasons | LINE: 224 | FILE: /membri/pacinottitaranto/TCExam/shared/code/tce_functions_session.php

The unique administrator correctly enters administrative area and can operate all functions. 

Last version of software TCExam and Database correctly upgraded to the 12.1 version.

What's the problem?

**Comment by nicolaasuni** [comment]
Seem like that the getmypid() function has been disabled in your system.
I'll see if I can replace it with something else.

**Comment by Pino50** [comment]
I use a free hosting: Altervista

**Comment by nicolaasuni** [comment]
I have pushed a change in the development version.

**Comment by nicolaasuni** [comment]
This appears to be resolved.
