### ISSUE TITLE
I make a clarification

### ISSUE THREAD

**Issue by Pino50** [tecnickcom/tcexam#252]
I upgraded an old installation of TCExam so I upgraded my database from version 11 to 12. 1 through the provided files ***.sql.
So, applying the second one (from 12 to 12.1) I got the following error:

ALTER TABLE tce_testsslcerts ADD Foreign Key (tstssl_test_id) references tce_tests (test_id) ON DELETE cascade ON UPDATE no action;
#1215 - Cannot add foreign key constraint

I noticed that the error is normally generated if the target table is non a innoDB table so the only way to go on the error was to change the tce_test table from myIsam to innoDB.

It could be helpful to report in documentation this (partial) issue.

**Comment by Pino50** [comment]
I upgraded an old installation of TCExam so I upgraded my database from version 11 to 12. 1 through the provided files ***.sql.
So, applying the second one (from 12 to 12.1) I got the following error:

ALTER TABLE tce_testsslcerts ADD Foreign Key (tstssl_test_id) references tce_tests (test_id) ON DELETE cascade ON UPDATE no action;
#1215 - Cannot add foreign key constraint 

I noticed that the error is normally generated if the target table is non a innoDB table so the only way to go on the error was to change the tce_test table from myIsam to innoDB. 

It could be helpful to  report in documentation this (partial) issue.

**Comment by nicolaasuni** [comment]
The tce_tests table was InnoDB also in version 11.
So, you should never face this problem using the original installation files.
