### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Psarmmiey** [tecnickcom/tcexam#253]
Hello, I keep getting this error when I run the software 

"Warning: require_once(../config/tce_config.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/tcexam/public/code/index.php on line 34

Fatal error: require_once(): Failed opening required '../config/tce_config.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/tcexam/public/code/index.php on line 34"

Please I need anyone that has a clone of this software that works immediately at first run

**Comment by Pino50** [comment]
Once correctly installed this software runs immediately. It seems thes's an installation problem. Are you sure of following the complete and correct procedure?

**Comment by nicolaasuni** [comment]
"If you are getting the TCExam source code for the first time, please rename the “config.default” folders inside admin, public and shared to “config”."
Ref. https://tcexam.org/docs/installation/

**Comment by vishwas2502** [comment]
anyone can explain me how to solve the problem
