### ISSUE TITLE
Guessing during  a test is easy in certain cases

### ISSUE THREAD

**Issue by peteri14** [tecnickcom/tcexam#255]
Yesterday I have discovered a serious problem with the testing system. During the test a lot of students were using the inspector functionality of the Firefox browser. I did not understand why, but now I think I understand. What happened is, that when I create a question and I start adding the answers I usually add first the correct answers and only afterwards the incorrect answers. This means that the correct answers have lower answer_ID.
I have attached two images. The first (test.png) image shows that the four answers have the following ID:
answer_4380
answer_4378
answer_4376
answer_4379
The second (test_question.png) image shows, how the tcexam lists the answers, as they were defined. (Sorry the question and the answers are in Hungarian, but I think it is more clear with images.) The first "correct" answer is "Érték" and it has the lowest answer_ID, which is obvious in the first (test.png) image, as answer_4376.

Of course it is not really an issue of the system, it is my "social" problem, but I feel that the system has to hide how, in what order, I have defined the answers.

My simple solution is, that I can export my whole question database and randomize the true and false answers in the XML file, but maybe others have this problem as well, so it would be nice to randomize the answer IDs or hide their definition order as well.

![test](https://user-images.githubusercontent.com/8905785/57720291-d7822480-7681-11e9-875e-24e33a331d99.png)
![test_question](https://user-images.githubusercontent.com/8905785/57720298-db15ab80-7681-11e9-9650-7a5577cd01d4.png)

**Comment by nicolaasuni** [comment]
It seems that you are using an old TCExam version.
Upgrading to the latest version should solve the problem.
