### ISSUE TITLE
Wrong behavior for checkboxes on test admin page

### ISSUE THREAD

**Issue by damms005** [tecnickcom/tcexam#257]
On the test admin page (_admin/code/tce_edit_test.php_), the _onclick_ handler for randomization checkboxes is reversed: it is when "random" is selected that "order" should be enabled

**Comment by nicolaasuni** [comment]
The "select" checkbox means "enable random selection".
The "order" checkbox means "enable random order".
When the "order" checkbox is disabled, then you can select a specific order type.

**Comment by damms005** [comment]
@nicolaasuni Don't you think it will be much helpful if you push a commit that will label these input elements exactly as you have [described them here](https://github.com/tecnickcom/tcexam/issues/257#issuecomment-516855515)? My thoughts
