### ISSUE TITLE
Multi Column PDF offline Tests Configiration

### ISSUE THREAD

**Issue by ghulamabbas93** [tecnickcom/tcexam#259]
Dear Sir,
 
              Currently, When we generate PDF, it comes on half of the page and rest remains empty. Could you please guide me how we can generate pdf test on two columns? It will save paper. 

Thanking you in anticipation.

Best Regards,

**Comment by nicolaasuni** [comment]
Unfortunately there is no option for that right now.
Test are generated on a single page for easy content fitting.
