### ISSUE TITLE
Error Result Test

### ISSUE THREAD

**Issue by biasaja** [tecnickcom/tcexam#260]
error if statistic disable
how to fix ERROR: [2] A non-numeric value encountered | LINE: 68 | FILE: /home/web/www/html/htdocs/evaluasi2/shared/code/tce_functions_statistics.php

i use php 7.2 on apache
thanks

**Comment by nicolaasuni** [comment]
Closing this as duplicates https://github.com/tecnickcom/tcexam/issues/274
