### ISSUE TITLE
How to regrade the test result ?

### ISSUE THREAD

**Issue by mamans86** [tecnickcom/tcexam#263]
I am very enjoy with TCExam, but sometimes there's mistake from question maker when placing the right answer.

is it possible we can change the answer key to a question? or there are other ways to upgrade the exam results of the examinees

**Comment by nicolaasuni** [comment]
You can only regrade open questions.
For other types of question there is no UI option to do so to avoid tampering with results, however it is possible to manually edit the entries in the tce_tests_logs table.
If a question is wrongly set in the db the advice is to disable it and add a new correct one.
