### ISSUE TITLE
tcexam execution issue

### ISSUE THREAD

**Issue by madhu684** [tecnickcom/tcexam#266]
I have using this exam system for a long time. Now when i start exam for multiple people at the same time, the exam not started at once. After click the start button, instead of showing question it again redirect to the front page(test list). After several times of trying, it started. Also, some times some students are receiving less than 50 questions.

If some one can, plz help me to solve this issue

**Comment by nicolaasuni** [comment]
It looks like a performance issue.
I suggest to look at the database installation and follow online guides on how to improve performances. Also upgrading PHP and using caching systems.
