### ISSUE TITLE
XML file upload issues?

### ISSUE THREAD

**Issue by cjw070** [tecnickcom/tcexam#270]
Hi, I'm trying to upload an XML file containing the questions I need for a module/topic. Here's what I've done so far:

- Create module/topic;
- Create a single MC question for that topic;
- Navigate to "list" and click the "XML" button at the bottom of the page to generate a "template" file;
- Fill this template file with the updated questions etc;
- Save the file in XML format and upload to TCExem via "import";
- TCExam shows message "MESSAGE:testupload1.xml: file sent correctly;

Unfortunately, after saying it's been successful, the questions are not uploaded to the module/topic correctly. The topic/module instead stays unchanged. 

Any suggestions on how to fix this?

**Comment by nicolaasuni** [comment]
Have you tried the TSV format instead? I wonder if it is a format problem or some syntax error?

**Comment by syahjo** [comment]
Try This.
1. Create 2 or more sample question/answer  for dummy export then Go to Questions List.
2. Export TSV all, open using import data from MSExcell.
3. Edit/add your desired question/answer **make sure it use same format dummy above it**.
4. Then save as to **Tab delimited** .txt
5. go to Question Importer chose tsv, browse , and klik send.

Well it's for me.

[Git_tcexamimpor_Tab_delimited.txt](https://github.com/tecnickcom/tcexam/files/4001313/Git_tcexamimpor_Tab_delimited.txt)

**Comment by SatheeshKumarS26** [comment]
How to add the imported .txt file in topics? I don't find any reference. Appreciate any help.
