### ISSUE TITLE
Bootstrap theme for TCExam

### ISSUE THREAD

**Issue by edahkaben** [tecnickcom/tcexam#271]
Is there any bootstrap based theme for TCExam? So test taker feel comfort when open the test from mobile device.

**Comment by nicolaasuni** [comment]
TCExam only comes with a default CSS.

**Comment by mamans86** [comment]
Hi. I have built the custom theme for TCExam, currently this theme is applied to public area.
Fortunately this theme is looks like Bootstrap, you can find the theme here https://picoman-theme.blogspot.com/
