### ISSUE TITLE
Redistribute modified TCExam

### ISSUE THREAD

**Issue by edahkaben** [tecnickcom/tcexam#272]
if I make changes to the tcexam code, am I allowed to distribute the modified version to others. for example, I modified the theme for TCExam (CSS, JS and some PHP) and then shared it with others, is that allowed?

Regards.

**Comment by nicolaasuni** [comment]
What is allowed is explained in the LICENSE file:
https://raw.githubusercontent.com/tecnickcom/tcexam/develop/LICENSE.TXT
