### ISSUE TITLE
Error When Viewing Exams Result

### ISSUE THREAD

**Issue by udarifki** [tecnickcom/tcexam#274]
Hi everyone

I'm using TCExam for semester exams in my school. I got error message when trying to view exams result for some groups. The error message like: **ERROR: [2] A non-numeric value encountered | LINE: 68 | FILE: C:\xampp\htdocs\ujian\shared\code\tce_functions_statistics.php**

Is there any solution for this error? Thank you
![ERR](https://user-images.githubusercontent.com/57903361/70505124-c76bee00-1b59-11ea-864f-da4f9f35d7ad.jpg)

**Comment by nicolaasuni** [comment]
Which version of TCExam are you using?

**Comment by udarifki** [comment]
I am using TCExam ver 14.1.3

**Comment by nicolaasuni** [comment]
This has been fixed several releases ago.
Please upgrade.
