### ISSUE TITLE
Time Zone still incorected :(

### ISSUE THREAD

**Issue by syahjo** [tecnickcom/tcexam#282]
Hi @nicolaasuni & team.

Just install latest version.
Deploy it on php 7.
Running great, for 5 student test.
onscreen student view test right top corner show local computer time okay.

but,...

On Admin test result/review get different time (gmt+0).
the server was configure (php.ini) okay, other apps work fine with GMT+7 Asia/Jakarta TZ.

.htacces was config GMT+7 
have search & follow tcexam set config tutorial patch.
unfortunetly still not resolved.

Will Apreciate any comment, or trick or anything will do help.

Matursuwun.

**Comment by nicolaasuni** [comment]
Check shared/config/tce_config:
define('K_TIMEZONE', 'UTC');

**Comment by nicolaasuni** [comment]
Try to set the timezone in shared/config/tce_config.php:
`define('K_TIMEZONE', 'UTC');`
and uncomment the line:
`//date_default_timezone_set(K_TIMEZONE);`
