### ISSUE TITLE
ATTENTION: [8192] Function get_magic_quotes_gpc() is deprecated | LINE: 306 | FILE: /srv/http/TCExam_16/shared/config/tce_config.php

### ISSUE THREAD

**Issue by rekja** [tecnickcom/tcexam#284]
Hi,

after the last upgrade to PHP 7.4.1, the following message began to appear:

ATTENTION: [8192] Function get_magic_quotes_gpc() is deprecated | LINE: 306 | FILE: /srv/http/TCExam_16/shared/config/tce_config.php

Regards
Jarek

**Comment by didiwebid** [comment]
Disable the 'if'

**Comment by wecomfy** [comment]
> Disable the 'if'

Which 'if' ? Because there are some 'if's here
![15848484558013053311087469602182](https://user-images.githubusercontent.com/62492777/77241775-ac654b80-6c29-11ea-85c9-723ebae85e11.jpg)

**Comment by didiwebid** [comment]
![ifano](https://user-images.githubusercontent.com/60571533/77241845-9441fc00-6c2a-11ea-8a8d-ef1fff55fdce.png)

Function get_magic_quotes_gpc() always returns false on latest PHP

**Comment by nicolaasuni** [comment]
This has been fixed in 14.2.2
