### ISSUE TITLE
Tried Exporting Results to tsv or pdf

### ISSUE THREAD

**Issue by saphemmy** [tecnickcom/tcexam#287]
I got the error: <div class="warning">ATTENTION: [8192] Function create_function() is deprecated | LINE: 549 | FILE: /var/www/html/Examz/shared/code/tce_functions_general.php</div>
when i tried exporting over 1000 users result to either tsv or pdf. Please what is the way Forward?

**Comment by nicolaasuni** [comment]
This has been fixed in TCExam 14.2.2.
