### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by marckatznelson** [tecnickcom/tcexam#288]
I downloaded the files from GitHub and added then under htdocs/exam folder. Upon typing http://xyx.com/exam/install/install.php in firefox, I only see a blank screen,

is there anything else I should do before installing via browser?

**Comment by nicolaasuni** [comment]
Be sure you are following the installation guide at https://tcexam.org/docs/installation/ and check the error logs in your web server.
You can also install TCExam manually by setting up the Database and copy/edit the configuration files.
