### ISSUE TITLE
Unable to set the Time Zone correctly

### ISSUE THREAD

**Issue by samsri321** [tecnickcom/tcexam#292]
[screen shot TCEXAM.docx](https://github.com/tecnickcom/tcexam/files/4452959/screen.shot.TCEXAM.docx)
HI Nicolaasuni & teamates

I just installed TCexam at my Institute on windows sever 2012, IIS 8.5. PHP 7.2.29 and MariaDB. Things are working fine except the time.  The time displayed on the right top corner is absolutely correct. But
the time displayed under the tab "test---->Result summary" is different. Time in my PHP.in is set to Asia/Dili TZ and my server machine is also configured with UTC TZ +05:30 as I belong to INDIA. The constant i "K_TIMEZONE"n file tce_config.php under config directory of the shared folder is set to UTC. I tried a lot to fix it but all in vain. I am attaching the screen shot of result summary page you can verify that time displayed at top right corner is different as the time displayed in the summary in the column "start time".

**Comment by samsri321** [comment]
I have solved this by setting the K_TIMEZONE variable equal to "Asia/Calcutta" and it works fine now so the issue can be closed

**Comment by AmritasyaPutra** [comment]
Yeah, Asia/Dili seems to be problematic. I had to set Asia/Kolkata to make it work.
