### ISSUE TITLE
Problem with timer - URGENT!

### ISSUE THREAD

**Issue by lukenavo** [tecnickcom/tcexam#293]
Hi,
I have had some trouble with an assesment with 50 students. I choosed to put a timer in every question (for example 60 sec for single answer, 120 for m/c, etc).
The problem was that (sometimes and not with every students) while students attend a question tcexam shift to the next question before the time set. In the final report shifted questions result without any IP address (0.0.0.0). 
Tcexam is hosted on a altervista web server. Is there some tricks for skip this problem? I looked on timer.js file setting but I can't understand very much...

Thank you for any hints

**Comment by nicolaasuni** [comment]
Not sure what is happening there, it will need some investigation on your side if possible.

**Comment by nicolaasuni** [comment]
Closing this for lack of feedback.
