### ISSUE TITLE
Unable to generate PDF

### ISSUE THREAD

**Issue by pnclvo** [tecnickcom/tcexam#294]
Hi, 
I am not an expert and I had some problems in the installation, but I finally have a working install of TCExam.
I am able to generate online exams.
But if I try to generate PDF files for offline tests, I get the following error message:
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/tcexam/admin/code/tce_pdf_testgen.php
TCPDF ERROR: Some data has already been output, can't send PDF file

Could someone help me?
Thanks,
Pier

**Comment by jpbhimani** [comment]
Same problem here

**Comment by jpbhimani** [comment]
Download the latest version of TCExam....

**Comment by rdk187** [comment]
Hello, 
I have the same issue. When I try to generate a PDF of any test I get:
[ATTENTION]: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /htdocs/tcexam/admin/code/tce_pdf_testgen.php

I'm using TCExam ver. 14.2.3.

My OS is:
OpenBSD 6.7 (GENERIC.MP) #1: Sat May 16 16:33:02 MDT 2020
    root@syspatch-67-amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP

#pkg_info | egrep http\|php\|sql\|aria
mariadb-client-10.4.12v1 multithreaded SQL database (client)
mariadb-server-10.4.12v1 multithreaded SQL database (server)
nghttp2-1.40.0      library for HTTP/2
p5-DBD-mysql-4.050  MySQL drivers for the Perl DBI
php-7.4.5p0         server-side HTML-embedded scripting language
php-curl-7.4.5p0    curl URL library extensions for php
php-gd-7.4.5p0      image manipulation extensions for php
php-mysqli-7.4.5p0  mysql database access extensions for php
php-pgsql-7.4.5p0   pgsql database access extensions for php
postgresql-client-12.2 PostgreSQL RDBMS (client)
sqlite3-3.31.1p0    embedded SQL implementation

I also get some other errors, maybe they all are related:
1. 
I can create w directory i /cache/* but whet I try to upload something I get error:
[ERROR]: model.png: unable to send the file

/cache permission is set to:
drwxrwxrwx  7 www   www      512 Jun  6 19:36 cache

2.
I can add questions to tests, but then I can't delete them from the test - when I push DELETE i get blank page "Test management"

3.
When I try to upload users from file I get:
User Importer
ERROR: 2012Kosz_Inf1.txt: unable to send the file

Did I missed something in my conf?
Any help will be appreciated. 
Thanks!

**Comment by nicolaasuni** [comment]
Please try to upgrade to the latest version.

**Comment by jgun98vpn4** [comment]
I have the latest tcexam but still get error 
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of type null | LINE: 586 | FILE: /var/www/html/tcexam/admin/code/tce_pdf_testgen.php
ATTENTION: [8] Trying to access array offset on value of typ

**Comment by jgun98vpn4** [comment]
TCExam ver. 14.8.5 - Copyright © 2004-2020 Nicola Asuni - Tecnick.com LTD
