### ISSUE TITLE
Session write returns database resource instead of true

### ISSUE THREAD

**Issue by fdevibe** [tecnickcom/tcexam#295]
It seems the session write function needs to return `true` or `false` proper. The documentation is not clear on this (https://www.php.net/manual/en/function.session-set-save-handler.php), perhaps this has changed in recent versions of PHP without the docs being updated? It also seems that `F_db_query` bahves differently with postgres and mysql. `mysql_query()` will return a database resource on a successful `SELECT`, `SHOW`, `DESCRIBE` and `EXPLAIN`, while all other queries will return `true` on success (https://www.php.net/manual/en/function.mysql-query.php). `pg_query()` returns a resource on success in all cases (https://www.php.net/manual/en/function.pg-query.php).

With PHP 7.4.6 using postgres, I get the error

    ERROR: [2] Unknown: Session callback expects true/false return value | LINE: 0 | FILE: Unknown
    ERROR: [2] Unknown: Failed to write session data using user defined save handler. (session.save_path: ) | LINE: 0 | FILE: Unknown

at the bottom of every page.

**Comment by nicolaasuni** [comment]
Fixed on develop branch. I will merge it soon to master.
