### ISSUE TITLE
TCExam on Ubuntu Server 20.04 LTS and PHP 7.4

### ISSUE THREAD

**Issue by beish** [tecnickcom/tcexam#299]
Hello,
first, I want to say that you doing a great job with both tcpdf and tcexam softwares.

My question is: Is it possible to setup tcexam on Ubuntu Server 20.04 LTS with PHP 7.4 version and MySQL 8?

I've used tcexam earlier on ubuntu server 14 with PHP 5 and all worked like a charm but with newer versions, I can't manage it to work with OMR scanned images.
When I import answers I just got a blank page with nothing on it, no errors showed on page or ERROR: the image of OMR DATA page is missing or unreadable
![tcexam](https://user-images.githubusercontent.com/42480143/84940166-b9d28a80-b0df-11ea-9285-3b3a0470bb54.png)
![tcexam1](https://user-images.githubusercontent.com/42480143/84946953-be9c3c00-b0e9-11ea-9643-250cf992b896.png)

**Comment by nicolaasuni** [comment]
It should be possible.
Please enable max error reporting in PHP to see any error.
