### ISSUE TITLE
Make Money from TCExam 

### ISSUE THREAD

**Issue by edahkaben** [tecnickcom/tcexam#300]
Hi nicola, if I create small community of tcexam user and i give the community support like help installing, troubleshooting, patching, customizing and etc, may i allowed to make money from what i do in this community?
i know that TCExam is licensed under dual licensing, open source and commercial license with usage case.
I read that i can make money from selling open source program. Is this applied too to TCExam that has Dual Licensing?

**Comment by nicolaasuni** [comment]
To purchase licenses please contact Tecnick.com directly.
