### ISSUE TITLE
Modernize User Interface

### ISSUE THREAD

**Issue by andiplusplus** [tecnickcom/tcexam#315]
TCExam is great, but the current user interface is quite old if compared to the latest technology. Is there any plan to bring UI Framework like Bootstrap, Bulma, etc to improve user experience and give more appealing look. I hope TCExam great in back-end and also front-end.

**Comment by mamans86** [comment]
Hi, seems TCExam Will moving forward to modernize user interface. The current version is already mobile friendly although using standard style for color scheme. 
you can adjust several style to button and other elements and add some setting CSS media query.
.
The current version need some tweak in navigation, so the menu fits on smaller device.

**Comment by nicolaasuni** [comment]
I have added the possibility to specify custom themes in TCExam 14.4.0 (now in the develop branch).
The K_PUBLIC_THEME and K_ADMIN_THEME can be used to define the public and admin themes respectively.
The "config/theme/" folder has been added to be able to include custom theme scripts.
In this way every user can keep their custom themes locally avoiding to be overwritten by new versions.

**Comment by mamans86** [comment]
Good news, i have built the custom theme for TCExam, currently this theme is applied to public area.
you can find the theme here https://picoman-theme.blogspot.com/
