### ISSUE TITLE
Error on registration

### ISSUE THREAD

**Issue by genomorro** [tecnickcom/tcexam#316]
If a new user is registred I can read:

```
Cannot add or update a child row: a foreign key constraint fails (`vrootomj_tcex282`.`tcs5_usrgroups`, CONSTRAINT `tcs5_usrgroups_ibfk_2` FOREIGN KEY (`usrgrp_group_id`) REFERENCES `tcs5_user_groups` (`group_id`) ON DELETE CASCADE ON UPDATE NO ACTION)
```
My config is:

```
$regfields = array(
    'user_email' => 2,
    'user_regnumber' => 0,
    'user_firstname' => 2,
    'user_lastname' => 2,
    'user_birthdate' => 0,
    'user_birthplace' => 0,
    'user_ssn' => 2,
    'user_groups' => 1,
    'user_agreement' => 0
);
```
If I use the admin form everything is ok. I think that's the basic information but if you need other just ask me.

**Comment by mamans86** [comment]
What is your stack? XAMPP/LAMPP or other?

**Comment by genomorro** [comment]
I'm using a LAMP stack in a cloudamo hosting, but I've replicated this issue in Debian 10.

**Comment by nicolaasuni** [comment]
Are you using a genuine latest version of TCExam from the master branch of this website?
Are you using the original MySQL DB schema?

**Comment by genomorro** [comment]
Hi. Yes and no. I used 14.3.2 tag from github. In that moment was the most recent release. I was using a MariaDB schema. I tried also with PostgreSQL, so I thing that my DB was ok.

Currently I'm not using TCExam because of this bug, however I can try again with the correct instructions.

**Comment by nicolaasuni** [comment]
Unfortunately I am unable to reproduce this issue.
Please try to use the latest TCExam version with a fresh install.
