### ISSUE TITLE
Adding mobile number verification on user registration

### ISSUE THREAD

**Issue by manishamittal16** [tecnickcom/tcexam#324]
Hi
I need mobile number field with otp verification but i am not able to do that ,getting Undefined index problem when adding new field.And from where I access html that contains registration page UI .

**Comment by nicolaasuni** [comment]
You can probably do that easily using a verify API service like:
https://www.vonage.co.uk/communications-apis/verify/

**Comment by manishamittal16** [comment]
Thank You,
Already done with this.
