### ISSUE TITLE
Please provide alternative logo like flat design mode, variation color like monochromatic, black, white

### ISSUE THREAD

**Issue by edahkaben** [tecnickcom/tcexam#325]
Hi, i think it's very nice if TCExam provide alternative logo design, such as flat design logo. And cool enough if any color variation of logo in TCExam like Monochrome, black and white logo is provided too.

**Comment by nicolaasuni** [comment]
I have added a black/white and grey versions in 14.4.0

**Comment by gnadnog** [comment]
Hi Nicola, thanks for the great TCExam. Would you like to include these additional logos in the next TCExam release. I think these logos give TCExam a cool feel, and look to match the current TCExam theme as well as any additional themes.
![logo_tcexam_white_noborder_transparent_114x21](https://user-images.githubusercontent.com/76911002/104865377-6292e200-596e-11eb-9fc2-86f6b859b6dc.png)
![logo_tcexam_black_newborder_transparent_118x25](https://user-images.githubusercontent.com/76911002/104865378-64f53c00-596e-11eb-95b2-6df3943ba2e3.png)
![logo_tcexam_black_noborder_transparent_114x21](https://user-images.githubusercontent.com/76911002/104865381-658dd280-596e-11eb-8d39-cf0350af99a6.png)
![logo_tcexam_newborder_118x25](https://user-images.githubusercontent.com/76911002/104865383-658dd280-596e-11eb-8e3c-49155bb9f384.png)
![logo_tcexam_newborder_transparent_118x25](https://user-images.githubusercontent.com/76911002/104865385-66266900-596e-11eb-8a1c-0c8f3d6d1a7e.png)
![logo_tcexam_noborder_114x21](https://user-images.githubusercontent.com/76911002/104865386-66beff80-596e-11eb-96c1-4a3f89a2f60f.png)
![logo_tcexam_noborder_transparent_114x21](https://user-images.githubusercontent.com/76911002/104865387-67579600-596e-11eb-8c04-4456ec05b831.png)
![logo_tcexam_white_newborder_transparent_118x25](https://user-images.githubusercontent.com/76911002/104865388-67f02c80-596e-11eb-972e-3f614a74dc42.png)
