### ISSUE TITLE
Is it legal using TCExam Logo that displayed on the tcexam.org

### ISSUE THREAD

**Issue by andiplusplus** [tecnickcom/tcexam#332]
Is it legal if i change TCExam logo on header with TCExam logo that displayed on tcexam.org?
Personally i like flat design logo in the tcexam.org logo, and i want put that logo on  TCExam header.

**Comment by edahkaben** [comment]
hi Nicola, i think it's very nice if you provide TCExam logo that appear on tcexam.org as an alternative logo.
Cheers

**Comment by edahkaben** [comment]
i think flat design with no border image will make TCExam looks cool

**Comment by nicolaasuni** [comment]
Please keep the provided logo unless you have a commercial license.
