### ISSUE TITLE
Failed to delete already inserted question after adding it to test

### ISSUE THREAD

**Issue by andiplusplus** [tecnickcom/tcexam#333]
This issue occurred when i create test, then add some question to the test. When i click delete link to remove the inserted question, it only show white blank page, there is no error message or warning. When i press browser back button, the question is remain there.
I hope this issue is fixed as soon as possible. Thanks, regards.

**Comment by mamans86** [comment]
Thanks for posting this issue, i already see that problem too. We will fix this issue as soon as possible. 😉
