### ISSUE TITLE
Please allow each topic to be a permanent member of multiple modules (not just one module)

### ISSUE THREAD

**Issue by dmusdev** [tecnickcom/tcexam#335]
Hello, we know that, when creating a test, we can combine any topic from any module. However, that does not meet our needs at all. 

We need to have a module of topics for each grade, where some of the topics must be shared by two grades (i.e. by two modules), as a form of regular revision (English language learning absolutely needs this).

So to sum up, please implement an ability for a single topic to be possible to be assigned to multiple different modules **permanently**.

Thank you.

**Comment by mamans86** [comment]
i think your requirement may need big change of TCExam codebase.
the alternative way, you can copy some topic to other module through Module -> List Menu

**Comment by dmusdev** [comment]
> 
> 
> i think your requirement may need big change of TCExam codebase.
> the alternative way, you can copy some topic to other module through Module -> List Menu

So does that mean you are going to implement it? I'm quite surprised nobody needed that yet in the past what 14 years this has been in development?

**Comment by nicolaasuni** [comment]
You can think of Modules and Topics just like arbitrary groups to better classify the questions, then in each test you can combine any module and topic as you wish.
For example, if you have questions that apply to multiple grades you can create either a module or a topic to put these "shared" questions.
