### ISSUE TITLE
PDF Tests NOT download on IDM

### ISSUE THREAD

**Issue by ghulamabbas93** [tecnickcom/tcexam#336]
Hi ,

I have found an issue with download of PDF tests on IDM. Tests do not download if IDM is installed. IDM catches the download link but does not proceed.

What is solution to this?

**Comment by nicolaasuni** [comment]
What is IDM?

**Comment by ghulamabbas93** [comment]
IDM is Internet Download Manager which is used to download PDFs,Videos and other stuff on the Internet.

**Comment by nicolaasuni** [comment]
This seems not a TCExam issue but rather an IDM one.
Maybe there is an option to disable IDM for a specific website?
