### ISSUE TITLE
Set answer to be required

### ISSUE THREAD

**Issue by beish** [tecnickcom/tcexam#338]
Is it possible to set that user can not go further in test if the answer is not checked, required answer to question?

**Comment by nicolaasuni** [comment]
The only thing that may come close is using the "fullscreen" + "automatic next" on the questions editor and disable "questions menu" option in the test editor.

Note that while it offers some flexibility, TCExam is actually designed to promote some testing models. In particular one where the use has the opportunity to revise the answers until the test is up. In contrast there is the above mode where you can also force a timeout per each question (like in some psychological tests).

**Comment by beish** [comment]
Thanks for answer Nicola
