### ISSUE TITLE
Is there a limit to the number of questions within the tcexam application?

### ISSUE THREAD

**Issue by beish** [tecnickcom/tcexam#339]
Hello,
Is there a limit to the number of questions within the tcexam application? 
We need to create one thousand questions pool and after that we would create tests with a hundred random questions from those pool of thousand questions.

**Comment by nicolaasuni** [comment]
There are no implicit limits in the software but you'll have to size your infrastructure adequately.

**Comment by beish** [comment]
Thanks for answer Nicola
