### ISSUE TITLE
Still having issues with PDF creation

### ISSUE THREAD

**Issue by samarita** [tecnickcom/tcexam#34]
Hello,

I installed the new version (12.1.0110), but now I am getting the following error:

LET OP: [8] Undefined index: '403' | LINE: 232 | FILE: /xxxx/xxxxxxx/public_html/xxxxx/admin/code/tce_pdf_results.php
TCPDF ERROR: Some data has already been output, can't send PDF file.

Can you please take another look?

Thanks.

**Comment by tuny4me** [comment]
PLS I GET THIS ERROR WHEN I CLICK ON GENERATE PDF OFFLINE TEST
ATTENTION: [8] Undefined offset: 0 | LINE: 770 | FILE: C:\wamp\www\frsconlineexam\admin\code\tce_pdf_testgen.php
TCPDF ERROR: Some data has already been output, can't send PDF file

**Comment by infomate** [comment]
I installed TCEXAM on my x10hosting account using the one click installers.  I am assuming that all the default file/directory permisions should have been taken cared of.  On my new installation I was able to finish 1 exam and tried to PDF print it several times. I tried editing the the tce_pdf.php to change the PDF title/address/logo. when I tried to print, the system show the  ATTENTION: [8] Undefined offset: 0 | LINE: 770 | FILE: \. \.\admin\code\tce_pdf_testgen.php.  I have undone what I edited on the tce_pdf file but the error was still there. I re-checked the folder and file permissions and found all files with 644 and folders with 755.  I AM LOST. .  . . Please help!
