### ISSUE TITLE
TCPDF creation of user test results

### ISSUE THREAD

**Issue by beish** [tecnickcom/tcexam#344]
I'm using TCExam for testing purposes and when need to create answered questions PDF I've got this printed on document.
###################
correct: ( 0%)
wrong: ( 0%)
unanswered: ( 0%)
undisplayed: ( 0%)
points: 1.000 / 5.000 ( 20%)
###################
Everything is OK but why there is no percents for correct/wrong answers included?
Or where in TCExam files i can exclude this data from printing on created PDF document?

**Comment by nicolaasuni** [comment]
Thank you for reporting this issue.
It is now fixed in the development branch that will be merged soon.
