### ISSUE TITLE
PicoMan - The Mobile First Design Custom Theme for TCExam

### ISSUE THREAD

**Issue by mamans86** [tecnickcom/tcexam#347]
I just built a new theme for TCExam. This theme uses Pico.css as its base. Mobile First Design, and has a look like Bootstrap. Has the ability to increase or decrease the text size on the question page. Has the ability to mark questions that are still in doubt. You can learn more about this theme at https://picoman-theme.blogspot.com/.

**Comment by mamans86** [comment]
@nicolaasuni if you don't mind you can merge this theme to this repo, i have made a pull request for this

**Comment by mamans86** [comment]
demo picoman theme https://esmk.yayasan-gondang.com/cbt/tceori/1/public/code/tce_login.php
username : picoman
password: picoman123

**Comment by nicolaasuni** [comment]
Thank you for your contribution.
Your PRs were merged with some minor changes.
