### ISSUE TITLE
Links to questions in Test Results Summary do not update Module/Topic context

### ISSUE THREAD

**Issue by tsfstarr** [tecnickcom/tcexam#352]
Hi,

I noticed the following bug when navigating Test Results Summary (Tests > Results), path "/tcexam/admin/code/tce_show_result_allusers.php".

When selecting "Statistics > Question", there is a hyperlink to each question in the left columns, denoted Q#.
<img width="54" alt="tcexam_questionlink" src="https://user-images.githubusercontent.com/26569749/103094716-5f6a3780-45f6-11eb-92b8-f185ef06266a.png">

This leads to the Question Management page with path "/tcexam/admin/code/tce_edit_question.php?question_id=80".
On this page the module and topic fields are not updated properly.
<img width="121" alt="tcexam_questionlink_linked" src="https://user-images.githubusercontent.com/26569749/103094613-fd113700-45f5-11eb-8664-a9058c410e1d.png">

When navigating to the question manually via menus, the module and topic fields are updated.
<img width="118" alt="tcexam_questionlink_navigated" src="https://user-images.githubusercontent.com/26569749/103094607-f8e51980-45f5-11eb-9b8c-92a58802cb15.png">

I'm guessing that this is something to do with the situations where query string variables are passed to instantiate the page correctly. Perhaps something like this:
"/tcexam/admin/code/tce_edit_question.php?subject_module_id=4&subject_id=12&question_id=80"

Kind regards

**Comment by nicolaasuni** [comment]
Thank you for reporting this.
Fixed in https://github.com/tecnickcom/tcexam/tree/14.5.1
