### ISSUE TITLE
MCMA Checkbox is always marked answered

### ISSUE THREAD

**Issue by gnadnog** [tecnickcom/tcexam#353]
Hai Nicola, thanks for the great work.
I found the strange situation that MCMA Checkbox (not radio button) is always marked answered.

When question contains MCMA with checkbox appear to user, the situation is normal, but if user switch to other question without pick an answer. That MCMA is marked answered.

Is this bug of TCEXAM or my setup issue?
Thanks in advance

Cheers

**Comment by nicolaasuni** [comment]
That is an intended feature.
When using the radio buttons for MCMA the user can select true/false or leave the default to unanswered.
When using the MCMA checkbox mode the user has only the true/false options, so the system assumes that the question is "answered" after it has been displayed. Note that in MCMA all answers can be false.

**Comment by gnadnog** [comment]
Thank you for answering. However, I think it will confuse the user if there are many questions in the list of questions. Test takers cannot differentiate question status. And participants will assume that he has done all the questions.
Thanks for your great support.

**Comment by gnadnog** [comment]
Maybe, It Will be nice if MCMA checkbox marked differently in questions list.
