### ISSUE TITLE
Error when user type correct answer on Free Answer Question

### ISSUE THREAD

**Issue by gnadnog** [tecnickcom/tcexam#354]
Hi Nicola, thank for this great TCExam.

I create a free answer question with correct answer predefined through Multiple-Answer Management.

When user type the correct answer, a warning comes up
**Warning: A non-numeric value encountered in ...shared/code/tce_functions_test.php on line 1557**

But when user type wrong answer no warning message appear.

Is this bug or my bad setup?
Thanks in advance.

Cheers

**Comment by nicolaasuni** [comment]
Thank you for reporting this issue.
I have fixed in the development branch that will soon be merged in main.
