### ISSUE TITLE
Is it possible to load all question in one page?

### ISSUE THREAD

**Issue by gnadnog** [tecnickcom/tcexam#355]
Hi Nicola, thanks for this nice work.

I try several setting on TCExam, but can't find setting to load all question in one page, and save the question asynchronously to server via AJAX.

Is it possible to implement this feature on the next release?

We need this feature to minimize network traffic.

Thanks in advance.
Cheers

**Comment by nicolaasuni** [comment]
You can use one of the export buttons in:
admin/code/tce_show_all_questions.php

**Comment by gnadnog** [comment]
Thanks for answer, i know this featured on admin area, but my question is spesific to public area side (Test taker), is it possible to load all question in public side when test taker take assessment.
Thanks in advance, and thanks for your great support.

**Comment by nicolaasuni** [comment]
On the public interface there is the possibility to display the menu with all the questions.
Displaying all questions at once poses a lot of different challenges and makes little sense in an interactive test system.
