### ISSUE TITLE
Excel / Word Import question format 

### ISSUE THREAD

**Issue by gnadnog** [tecnickcom/tcexam#356]
Hi Nicola, thanks for your great support to TCExam. I know that TCExam provide question import in XML or TSV format. 
For most user (non tech user, like teacher) this file format is unordinary. Is there any tool to create question with XLSX or DOCX and then convert it to XML.
Do you have a plan to add additional file type to import question?
Thanks in advance.
Cheers

**Comment by nicolaasuni** [comment]
The data to be imported needs a structure, hence the XML or TSV format that are easily portable.
Note that TSV is compatible with spreadsheet software like LibreOffice Calc or MS Excel.
