### ISSUE TITLE
How to use Custom Mobile Theme

### ISSUE THREAD

**Issue by gnadnog** [tecnickcom/tcexam#357]
Hi Nicola, thanks for this great TCExam.
In version 14.5.0 i see that TCExam include a new custom mobile theme. By the way, how we use that? It is not documented yet in tcexam.org website. 
Thanks in advance.
Cheers

**Comment by nicolaasuni** [comment]
In public/config/tce_config.php change K_PUBLIC_THEME from 'default' to "picoman".

**Comment by mamans86** [comment]
I think we need something like theme switcher that make TCExam looks appealing. :D
