### ISSUE TITLE
Scanning OMR Sheets.

### ISSUE THREAD

**Issue by girishpadia** [tecnickcom/tcexam#36]
1) How the OMR evaluation will identify which user has submitted the OMR answer sheet?

2) What should be the file format while scanning? jpg or png? color or grayscale? how much dpi?

3) Do I need to follow any naming conversion while saving these scanned files? If so how to handle the bulk scanning?

**Comment by SBhagat23** [comment]
hi, is there someone, who help me to come out from this problem  "the image of OMR DATA page is missing or unreadable".
