### ISSUE TITLE
Cannot perform login when access via ipwan 

### ISSUE THREAD

**Issue by quanhh1** [tecnickcom/tcexam#386]
When i perform submitting  at the login form the ipwan turned into "localhost/admin/... or "localhost/public..." and if i want to access successfully then i have to change my url part from "localhost" to "ipwan" and everything is solved. Is that a issue , sorry for my english. Thanks you sir. I used version 14.8.1

**Comment by mamans86** [comment]
I think it is not an issue. If you want flexibility you can change the path to: $_SERVER['HTTP_HOST']

**Comment by quanhh1** [comment]
Sory that is my misconfiguration at the initial installation, i leave "localhost" in field "host url".

**Comment by quanhh1** [comment]
> I think it is not an issue. If you want flexibility you can change the path to: $_SERVER['HTTP_HOST']

Exactly thank you so much 👍
