### ISSUE TITLE
TCExem installation: Uncaught Error: Call to undefined function pg_connect()

### ISSUE THREAD

**Issue by nhquangifi** [tecnickcom/tcexam#389]
I am installing TCExam (14.8.1) on my PC (Mint 20.2) folowing the guide in https://tcexam.org/docs/installation/. The "Browser installation" failed with the error
start TCExam installation............[OK]
start database installation.........[OK]

    create or replace database and get connection........
    Fatal error: Uncaught Error: Call to undefined function pg_connect() in /var/www/html/tcexam/shared/code/tce_db_dal_postgresql.php:47 Stack trace: #0 /var/www/html/tcexam/install/tce_functions_install.php(170): F_db_connect('localhost', '5432', 'postgres', 'mypasswd') #1 /var/www/html/tcexam/install/tce_functions_install.php(63): F_create_database('POSTGRESQL', 'localhost', '5432', 'postgres', 'mypasswd', 'tcexam', 'tce_', true, true) #2 /var/www/html/tcexam/install/install.php(92): F_install_database('POSTGRESQL', 'localhost', '5432', 'postgres', 'mypasswd', 'tcexam', 'tce_', true, true, 'install.log') #3 {main} thrown in /var/www/html/tcexam/shared/code/tce_db_dal_postgresql.php on line 47
Searching "pg_connect()" on shared folder, I don't find out this function. Please help.

Thank you.
Quang

**Comment by nicolaasuni** [comment]
Could you please retry with the latest version?
Closing this as it is quite old now.
