### ISSUE TITLE
Cookie PHPSESSID will be soon rejected because it has the “SameSite” attribute set to “None”

### ISSUE THREAD

**Issue by AmritasyaPutra** [tecnickcom/tcexam#392]
I get the following warning on Firefox:

Cookie “PHPSESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute.

I think this should be fixed for the next iteration.

**Comment by AmritasyaPutra** [comment]
PHP 7.3 above allows setting this in setcookie call. I fixed through my .htaccess file. There is a way to do this in php.ini also. But I think htaccess and php.ini are too broad, this should be fixed at application level. Many users will be running without secure option.

**Comment by nicolaasuni** [comment]
This was solved in the 16.1.0 version.
More cookie options were added:
https://github.com/tecnickcom/tcexam/commit/9c63df784e126ccac323ca65c4e0ace9c2b83fd5
