### ISSUE TITLE
ERROR: SMTP connect() failed. IN tecnick cbt software

### ISSUE THREAD

**Issue by olamic** [tecnickcom/tcexam#395]
i have been having issues with the software smtp
![Capture111](https://user-images.githubusercontent.com/52048776/125175122-c4464300-e17e-11eb-9d4f-39548d847f24.PNG)
![Capture111](https://user-images.githubusercontent.com/52048776/125175129-cad4ba80-e17e-11eb-906d-352cf0297a4a.PNG)

**Comment by nicolaasuni** [comment]
The email seems misconfigured.
Please check:
https://github.com/tecnickcom/tcexam/blob/main/shared/config.default/tce_email_config.php
