### ISSUE TITLE
resetting the password

### ISSUE THREAD

**Issue by priyanka18k** [tecnickcom/tcexam#397]
Hi there,
my reset password is not working.
After entering temporary password  (which is displayed on clicking the reset password link) shows wrong username or password, 
however I have checked that in public/code/tce_user_verification.php file password is updated successfully.

**Comment by nicolaasuni** [comment]
Have you tried to contact the system administrator? They can manually reset passwords.

**Comment by nicolaasuni** [comment]
stale comment - closing
