### ISSUE TITLE
A few issues..

### ISSUE THREAD

**Issue by arnabnaha** [tecnickcom/tcexam#4]
Hi..
Issues I found while testing tcexam
1. while registering a new user, the mini calendar beside the date of birth entry doesnt work..it just do nothing after clicking it.
2. after creating a new user, this is displayed on the next page: 
   ERROR: [1452]: Cannot add or update a child row: a foreign key constraint fails (`exam`.`tce_usrgroups`, CONSTRAINT `tce_usrgroups_ibfk_2` FOREIGN KEY (`usrgrp_group_id`) REFERENCES `tce_user_groups` (`group_id`) ON DELETE CASCADE ON UPDATE NO ACTION)
   but, the user is correctly added
3. when giving an exam and results are displayed to the user, there is a pdf button at the end of the page...when clicking that button, a new page opens but noting happen there...its simply a white page

**Comment by yomaz123** [comment]
How can i get the latest release
