### ISSUE TITLE
Error While Installation 

### ISSUE THREAD

**Issue by aviralsangal** [tecnickcom/tcexam#404]
Hi, I am installing TCEXAM on ubuntu 22.04 , php 8.1 and mysql 8. The installation page is stuck and following is the error in /var/log/apache2/error.log

[Fri Oct 28 01:11:54.291433 2022] [php:error] [pid 13006] [client 127.0.0.1:58258] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''utf8'' at line 1 in /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php:50\nStack trace:\n#0 /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php(50): mysqli_query()\n#1 /var/www/html/tcexam/install/tce_functions_install.php(170): F_db_connect()\n#2 /var/www/html/tcexam/install/tce_functions_install.php(63): F_create_database()\n#3 /var/www/html/tcexam/install/install.php(92): F_install_database()\n#4 {main}\n  thrown in /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php on line 50, referer: http://localhost/tcexam/install/install.php
[Fri Oct 28 01:12:59.286522 2022] [php:error] [pid 13008] [client 127.0.0.1:46058] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''utf8'' at line 1 in /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php:50\nStack trace:\n#0 /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php(50): mysqli_query()\n#1 /var/www/html/tcexam/install/tce_functions_install.php(170): F_db_connect()\n#2 /var/www/html/tcexam/install/tce_functions_install.php(63): F_create_database()\n#3 /var/www/html/tcexam/install/install.php(92): F_install_database()\n#4 {main}\n  thrown in /var/www/html/tcexam/shared/code/tce_db_dal_mysqli.php on line 50, referer: http://localhost/tcexam/install/install.php

![Screenshot from 2022-10-28 01-18-46](https://user-images.githubusercontent.com/12559720/198384671-3fe1b499-ee8c-41bc-bdde-fc0dd38213a7.png)

**Comment by nicolaasuni** [comment]
This has been fixed in the recent version 15
