### ISSUE TITLE
Error While Input Question

### ISSUE THREAD

**Issue by udarifki** [tecnickcom/tcexam#408]
Hello, I have a problem when submitting question, is there any solution to solve this?

ERROR: [1253]: COLLATION \'utf8_bin\' is not valid for CHARACTER SET \'latin1\'

Screenshot 
![image](https://user-images.githubusercontent.com/57903361/217430198-43b9f736-a7d8-4133-bd3b-05f9169af960.png)

**Comment by rfc-1149** [comment]
Hi. I have the same problem. Did you find any solution @udarifki ?

**Comment by udarifki** [comment]
hello, the problem solved by changing database collation from latin1_swedish_ci to utf8_unicode_ci
