### ISSUE TITLE
tce_show_result_allusers : problem when run in php ver 8 in delete , open , close ..

### ISSUE THREAD

**Issue by attia7** [tecnickcom/tcexam#411]
at file    admin/code/tce_show_result_allusers.php
line : 434  echo 'input type="hidden" name="itemcount" id="itemcount" value="'.$itemcount.'>" />'.K_NEWLINE; 

there is extra ">" sign after   value="'.$itemcount.'>" />'
Causes the function loop to stop in php ver 8  ; while it work in php 7 
when removed it the system run normally 
are this char ">" required in this place ?

**Comment by nicolaasuni** [comment]
Thank you I will fix this soon in the 15.0.3 version.
