### ISSUE TITLE
Tcexam is not GPL compliant

### ISSUE THREAD

**Issue by patty1954** [tecnickcom/tcexam#416]
According to the GPL, other conditions cannot be applied to a GPL licence.
You are in violation of the GPL and you will have to remove your extra conditions or you will be forced to by the GPL .

Soon I will be offering Tcexam as a free download without your restrictive conditions as they cannot be enforced according to the GPL.

You have been misleading people since 2005 and doing it intentionally.

**Comment by nicolaasuni** [comment]
Deleting this as it contains false and misleading statement.
