### ISSUE TITLE
Not login with default admin

### ISSUE THREAD

**Issue by rocnateb** [tecnickcom/tcexam#427]
Hello,

I have installed correctly, but when I try to log in with admin - 1234 it does not log in. Does not give error "ATTENTION: wrong user / password"
Anyone else has happened?
I am using ubuntu 24.04.
Thank you.

**Comment by AbdulRasheed8888** [comment]
When you run installation using localhost it successfully loged in, but when give Ip it is not logging in.

**Comment by rocnateb** [comment]
> When you run installation using localhost it successfully loged in, but when give Ip it is not logging in.
Hi Abdul,
Thank you for your reply.
Yes, that is exactly my problem. On the local machine, I can log in as admin, but on another machine on the same LAN, I can access the login panel, but when I enter the username and password, the system does nothing.

**Comment by AbdulRasheed8888** [comment]
Hi Rocnateb,
Please read login reload on this forum.
It will resolve your problem, basically Cooke setting has to set false
![Uploading Screenshot_20240626_163557.jpg…]()
 instead of true.
Mine problem is resolved

**Comment by rocnateb** [comment]
Thank you so much Abdul!!!
That's works for me too.

Change: 
sudo nano /var/www/html/tcexam/shared/config/tce_config.php

define('K_COOKIE_SECURE', true); -> define('K_COOKIE_SECURE', false);
define('K_COOKIE_HTTPONLY', true); -> define('K_COOKIE_HTTPONLY', false);

Cheers, have a great day!
