### ISSUE TITLE
Parse error: syntax error, unexpected T_STRING, expecting 

### ISSUE THREAD

**Issue by dwhofer** [tecnickcom/tcexam#6]
I tried to install this today on a 1and1 server, the install script ran fine, but I get this error when trying to do anything.

Parse error: syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /homepages/3/d155480421/htdocs/wsb3989035901/Agile/shared/code/tce_tmx.php on line 62

**Comment by yomaz123** [comment]
i'm having this error
Undefined index: t_warning in C:\wamp\www\tcexam-master\shared\code\tce_functions_errmsg.php on line 64

**Comment by yomaz123** [comment]
[2] file_get_contents(C:\wamp\www\tcexam-mastershared/config/lang/language_tmx.xml): failed to open stream: No such file or directory | LINE: 138 | FILE: C:\wamp\www\tcexam-master\shared\code\tce_tmx.php

**Comment by Hiddenreasure** [comment]
Che‎ck shared folder / config file / (installation path) /                                                                                                                                                                                                                                          From: yomaz123Sent: Tuesday, March 17, 2015 10:01 AMTo: tecnickcom/tcexamReply To: tecnickcom/tcexamSubject: Re: [tcexam] Parse error: syntax error, unexpected T_STRING, expecting  (#6)[2] file_get_contents(C:\wamp\www\tcexam-mastershared/config/lang/language_tmx.xml): failed to open stream: No such file or directory | LINE: 138 | FILE: C:\wamp\www\tcexam-master\shared\code\tce_tmx.php

—Reply to this email directly or view it on GitHub.

**Comment by nicolaasuni** [comment]
When you install TCExam the first time you have to create the configuration folder from the default one. Please have a look at the installation instructions at http://www.tcexam.org
