### ISSUE TITLE
TCPDF ERROR: The XObject Template '' doesn't exist!

### ISSUE THREAD

**Issue by gauravparashar** [tecnickcom/tcexam#66]
![screenshot from 2014-04-15 15 22 56](https://cloud.githubusercontent.com/assets/4403345/2705765/c60c64b4-c483-11e3-8edb-d5fa42cb7ab8.png)
While generating PDF from admin as well as users section it gives this error.
![screenshot from 2014-04-15 15 24 09](https://cloud.githubusercontent.com/assets/4403345/2705775/ee5cf5d2-c483-11e3-9480-e6383edb0dd5.png)

**Comment by mailtoiftikhar** [comment]
Hi, I am still getting this XObject template error even in the updated version of 2023. What could be the reason? Any help would be appreciated.
