### ISSUE TITLE
request password not working

### ISSUE THREAD

**Issue by samarita** [tecnickcom/tcexam#67]
Hello,

After I upgraded to the latest version the username and passwords are not accepted. I tried setting the K_STRONG_PASSWORD_ENCRYPTION constant
to FALSE on shared/config/tce_config.php, but that does not help.

So I tried requesting my password and I get the following error message: 

ERROR: [2] require_once(../../shared/phpmailer/class.phpmailer.php) [function.require-once]: failed to open stream: No such file or directory | LINE: 42 | FILE: /home/xxxx/public_html/xxxxxxx/shared/code/tce_class_mailer.php
# Fatal error: require_once() [function.require]: Failed opening required '../../shared/phpmailer/class.phpmailer.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/xxxx/public_html/xxxxxxxx/shared/code/tce_class_mailer.php on line 42

Any suggestions?

Regards,

**Comment by shogunverde** [comment]
Solo he perdido mi tiempo . Hago usuarios y la contraseña se genera pero es imposible entrar . Què hicieron esta vez. Con el pretexto de incrementar la seguridad destruyen todo
