### ISSUE TITLE
Fatal error in the install process

### ISSUE THREAD

**Issue by eimaster** [tecnickcom/tcexam#83]
## I started installing but a fatal error occurred and bellow is the output message:

TCExam - Installation

This is the installation script of TCExam by Tecnick.com LTD

DO NOT USE THIS SCRIPT FOR UPGRADING AN EXISTING INSTALLATION, INSTEAD READ UPGRADE.TXT

Please wait, this installation may take a while...

```
start TCExam installation............[OK]
start database installation.........[OK]
    create or replace database and get connection........[OK]
    create database tables..........
    Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\TCExam\shared\code\tce_db_dal_mysqli.php on line 87
```

**Comment by MishilDobariya** [comment]
Go to the C:\xampp\php
open php.ini file
search for max_execution_time in that file
change value max_execution_time=30 to max_execution_time=100
