### ISSUE TITLE
Problem at Installing Phase

### ISSUE THREAD

**Issue by eimaster** [tecnickcom/tcexam#84]
## I started installing tcexam but a fatal error occurred and here the error message:

TCExam - Installation

This is the installation script of TCExam by Tecnick.com LTD

DO NOT USE THIS SCRIPT FOR UPGRADING AN EXISTING INSTALLATION, INSTEAD READ UPGRADE.TXT

Please wait, this installation may take a while...

```
start TCExam installation............[OK]
start database installation.........[OK]
    create or replace database and get connection........[OK]
    create database tables..........
    Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\TCExam\shared\code\tce_db_dal_mysqli.php on line 87
```

**Comment by alghozi** [comment]
please help me,

**Comment by nicolaasuni** [comment]
Seems that the application is unable contact the database.
First, please check the installation guide and requirements at http://www.tcexam.org
Then be sure that the MySQL database is installed, the user and password are set and correct and the PHP-MySQL installation is working.
