### ISSUE TITLE
error 1226

### ISSUE THREAD

**Issue by samarita** [tecnickcom/tcexam#94]
Hello,

I am getting this error message:

ERROr: [1226]: User 'roosje' has exceeded the 'max_questions' resource (current value: 75000).

How can I make this go away as soon as possible"?
Regards,

**Comment by infohtreasure** [comment]
sorry Nicole will have to assist you on this error as i have not come across this error message before.

or can you explain what you want to achive before this error message come

Thanks

**Comment by samarita** [comment]
Hello,

I did not want to achieve anything in particular. I tried to login and this error message appeared.

Regards,

**Comment by nicolaasuni** [comment]
Please check the values in shared/config/tce_general_constants.php
