### ISSUE TITLE
Tasto "avanti" non mostrato

### ISSUE THREAD

**Issue by PaoloGiustiniani** [tecnickcom/tcexam#96]
Come da oggetto il tasto per proseguire e confermare la domanda non viene mostrato così come il tempo a disposizione rimanente.

Impostazioni errate?

**Comment by Hiddenreasure** [comment]
‎I use Google translate I want to be sure I'm right or better use English to make your request so as for us to help you, thanksAs object key to continue and confirm the application is not shown as well as the remaining time available. Wrong settings? - Is the translate correct?                                                                                                                                                                                                                                          From: Paolo GiustinianiSent: Wednesday, January 21, 2015 1:07 AMTo: tecnickcom/tcexamReply To: tecnickcom/tcexamSubject: [tcexam] Tasto "avanti" non mostrato (#96)Come da oggetto il tasto per proseguire e confermare la domanda non viene mostrato così come il tempo a disposizione rimanente.

Impostazioni errate?

—Reply to this email directly or view it on GitHub.

**Comment by PaoloGiustiniani** [comment]
Hello,
The "buttom" next isn't show in my question And time remaining is hidden.

**Comment by PaoloGiustiniani** [comment]
Hello,
I find the same problem on some versions of the demo (https://www.softaculous.com/demos/TCExam)

**Comment by nicolaasuni** [comment]
Please check the following guide:
http://www.tcexam.org/guide_first_test.php

**Comment by PaoloGiustiniani** [comment]
Hello Nicola,
I read the guide carefully.

Any suggestions?

**Comment by PaoloGiustiniani** [comment]
![test](https://cloud.githubusercontent.com/assets/5071623/5840831/9b9b022e-a198-11e4-8fb0-cbab909d38b2.png)

This is the output.

**Comment by PaoloGiustiniani** [comment]
Is a bug?

**Comment by nicolaasuni** [comment]
No, since I can't reproduce your issue.
From the screenshot colors seems that the software has been altered in some way.
Please be sure you are using the original version and follow the steps here:
http://www.tcexam.org/guide_first_test.php

**Comment by PaoloGiustiniani** [comment]
I have tried in another webserver (https://www.softaculous.com/demos/TCExam) same problem.

In my screenshot the color is "red" because i have modified *only* css.

**Comment by PaoloGiustiniani** [comment]
the problem is caused by some characters.
For examples ":"

**Comment by PaoloGiustiniani** [comment]
Could you test?

**Comment by PaoloGiustiniani** [comment]
Same problem with version 12.1.016 and  12.1.029

Can i send you my import?

**Comment by PaoloGiustiniani** [comment]
Sorry, this issue hasn't been solved.

**Comment by nicolaasuni** [comment]
I am unable to reproduce this issue.
Please be sure you are following the installation instructions at http://www.tcexam.org and the guide:
http://www.tcexam.org/guide_first_test.php
Please also be sure you are not selecting any advanced feature in que questions or test configuration.
