### ISSUE TITLE
Error Query Parameters

### ISSUE THREAD

**Issue by rtopete** [tecnickcom/tcexam#97]
After installation apperar one message with next legend:

ERROR: [2] mysqli_query() expects parameter 1 to be mysqli, null given | LINE: 87 | FILE: C:\inetpub\wwwroot\tcexam\shared\code\tce_db_dal_mysqli.php

Server environment:
Server: Windows Server 2012
IIS 8
DB: Mysql 5.2
PHP 5.6

Thanks in advance.
![phperror](https://cloud.githubusercontent.com/assets/10676809/5883451/15f17154-a318-11e4-95bb-8c04fb5464f7.png)

**Comment by nicolaasuni** [comment]
You probably have received some error messages during the installation process.
Try to repeat it and check if the MySQL user/password is working.
