### ISSUE TITLE
Non anonymous ldap connection

### ISSUE THREAD

**Issue by oyeaussie** [tecnickcom/tcexam#99]
Hello,

I am using v12.1.30 and trying LDAP authentication.

I see that the bind username is taken from the username field, which fails on our server as we dont allow anonymous binding. 
I get an error:
ERROR: [2] ldap_bind(): Unable to bind to server: Invalid DN syntax | LINE: 211 | FILE: /var/www/html/exam/shared/code/tce_altauth.php

My LDAP logs:

Feb 16 13:04:07 bckup1 slapd[20220]: conn=1015 fd=24 ACCEPT from IP=127.0.0.1:41764 (IP=0.0.0.0:389)
Feb 16 13:04:07 bckup1 slapd[20220]: conn=1015 op=0 do_bind: invalid dn (guru)
Feb 16 13:04:07 bckup1 slapd[20220]: conn=1015 op=0 RESULT tag=97 err=34 text=invalid DN
Feb 16 13:04:07 bckup1 slapd[20220]: conn=1015 op=1 UNBIND
Feb 16 13:04:07 bckup1 slapd[20220]: conn=1015 fd=24 closed

The above is if I use username "guru"

If I change the username to "cn=guru,cn=management,ou=Active,dc=bazaari,dc=com,dc=au" the bind is successful, but the user authentication fails.

LDAP logs:

Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 fd=24 ACCEPT from IP=127.0.0.1:41775 (IP=0.0.0.0:389)
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=0 BIND dn="uid=guru,cn=management,ou=Active,dc=bazaari,dc=com,dc=au" method=128
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=0 BIND dn="uid=guru,cn=management,ou=Active,dc=bazaari,dc=com,dc=au" mech=SIMPLE ssf=0
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=0 RESULT tag=97 err=0 text=
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=1 SRCH base="ou=Active,dc=bazaari,dc=com,dc=au" scope=2 deref=0 filter="(uid=uid=guru,cn=management,ou=active,dc=bazaari,dc=com,dc=au)"
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=1 SRCH attr=1.1 1.1 1.1 1.1 dn givenName mail sn
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=2 BIND anonymous mech=implicit ssf=0
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=2 BIND dn="" method=128
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=2 RESULT tag=97 err=49 text=
Feb 16 13:05:37 bckup1 slapd[20220]: conn=1017 op=3 UNBIND

As we dont allow anonymous binding and taking the username from the POST parameter is not working correctly, I tried adding 2 more constants into the configuration file:

/**
 * The DN for ROOT Account
 */
define ('K_LDAP_ROOT_DN', 'cn=root,dc=bazaari,dc=com,dc=au');

/**
 * The password for ROOT Account
 */
define ('K_LDAP_ROOT_PASS', 'xxxx');

and added the following line in the tce_altauth.php:

211 //                      if ($lbind = ldap_bind($ldapconn, $ldapusername, $ldappassword)) {
212                         if ($lbind = ldap_bind($ldapconn, K_LDAP_ROOT_DN, K_LDAP_ROOT_PASS)) {

Binding works, but the user does not get authenticated:

Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 fd=24 ACCEPT from IP=127.0.0.1:41852 (IP=0.0.0.0:389)
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=0 BIND dn="cn=root,dc=bazaari,dc=com,dc=au" method=128
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=0 BIND dn="cn=root,dc=bazaari,dc=com,dc=au" mech=SIMPLE ssf=0
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=0 RESULT tag=97 err=0 text=
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=1 SRCH base="ou=Active,dc=bazaari,dc=com,dc=au" scope=2 deref=0 filter="(uid=guru)"
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=1 SRCH attr=1.1 1.1 1.1 1.1 dn givenName mail sn
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=2 BIND anonymous mech=implicit ssf=0
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=2 BIND dn="" method=128
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=2 RESULT tag=97 err=49 text=
Feb 16 13:15:55 bckup1 slapd[20220]: conn=1020 op=3 UNBIND

Any suggestions?

Thanks,
Guru.

**Comment by nicolaasuni** [comment]
The version 12.2.0 should solve this problem.
I have added teh configuration entries K_LDAP_ROOT_DN and K_LDAP_ROOT_PASS and fixeed a bug in the $rdn array selection.

If you still experience problems after upgrade, please try to debug the tce_altauth.php file and print errors using ldap_error method.

**Comment by oyeaussie** [comment]
Hello Nicola,

Thanks for looking into this issue.

Now, I can authenticate the LDAP users fine. 

A couple of issues:
1) LDAP Attributes are not being mapped correctly. The values are all set to NULL. How can we troubleshoot this?
2) The IP address that its grabbing after LDAP authentication is IPV6, instead of IPV4. maybe I am just missing a parameter somewhere for this.

Also, if the LDAP value is not Null, the root dn and pass needs to be in single quotes ' ' otherwise we get an error:
[Sun Mar 29 13:00:27 2015] [error] [client 10.8.0.11] PHP Parse error:  syntax error, unexpected '=' in /var/www/html/exam/shared/config/tce_ldap.php on line 57
[Sun Mar 29 13:01:46 2015] [error] [client 10.8.0.11] PHP Parse error:  syntax error, unexpected '}' in /var/www/html/exam/shared/config/tce_ldap.php on line 63

maybe in next commit, you can add a line in the comment above the parameter explaining that.

Thanks,
Guru.

**Comment by nicolaasuni** [comment]
It should be fixed now in the 12.2.2 version. I finally manage to test it :-)
Please check the code of the tce_altauth.php file, I have added a commented line to print the returned structure of the LDAP entries.
